Repository keystonejs/keystone, pull requests merged in 2019-11, with the labels that each got.

#1891 Added missing colon to schema.md
  docs/guides/schema.md
Labels: needs-clarification

#1888 Add redirects from keystone-alpha to keystonejs
  website/static/_redirects
Labels: docs

#1911 The assignee type was a string
  docs/guides/add-lists.md
Labels: needs-clarification

#1912 Fix example in AdminUIApp README
  packages/app-admin-ui/README.md
Labels: needs-clarification

#1913 Improvements to checkbox field
  .changeset/small-fishes-cheer.md
  packages/arch/packages/controls/src/control.js
  packages/fields/src/types/Checkbox/views/Cell.js
  packages/fields/src/types/Checkbox/views/Controller.js
Labels: admin-ui, fields

#1914 Upgrade knex and pg dependencies
  .changeset/ten-impalas-hear.md
  package.json
  packages/adapter-knex/package.json
  yarn.lock
Labels: needs-clarification

#1919 Upgrade to latest changesets packages
  package.json
  yarn.lock
Labels: needs-clarification

#1920 Clean up changeset messages in preparation for a release
  .changeset/angry-hornets-wonder.md
  .changeset/loud-fans-vanish.md
  .changeset/neat-seahorses-melt.md
  .changeset/purple-gorillas-own.md
  .changeset/sharp-dots-march.md
  .changeset/short-pumas-switch.md
  .changeset/short-roses-call.md
  .changeset/small-fishes-cheer.md
  .changeset/three-kangaroos-attack.md
  .changeset/three-wolves-prove.md
  .changeset/unlucky-waves-carry.md
  .changeset/warm-camels-tie.md
  .changeset/wicked-ears-promise.md
  .changeset/wild-zoos-shout.md
  CONTRIBUTING.md
Labels: needs-clarification

#1926 Remove mongose-unique-validator
  .changeset/sixty-shoes-fly.md
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/adapter-mongoose/package.json
  yarn.lock
Labels: needs-clarification

#1931 App versioning
  .changeset/sour-melons-visit.md
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#1932 Fix broken changeset
  .changeset/ten-items-guess.md
Labels: needs-clarification

#1950 Upgrade jest dependencies
  .changeset/kind-bags-refuse.md
  package.json
  packages/build-field-types/package.json
  yarn.lock
Labels: needs-clarification

#1949 Update yarn.lock to silence errors from fsevents build
  yarn.lock
Labels: needs-clarification

#1960 docs: Update a typo in Schema - Lists & Fields
  docs/guides/schema.md
Labels: docs

#1968 Fixed Markdown snafu
  packages/fields/README.md
Labels: needs-clarification

#1963 Insensitive by default for text field filter
  .changeset/clever-owls-juggle.md
  packages/fields/src/types/Text/views/Controller.js
  test-projects/basic/cypress/integration/list-view-url-state_spec.js
Labels: needs-clarification

#1973 Use correct table alias in query builder
  .changeset/many-ants-cover.md
  CONTRIBUTING.md
  docs/guides/custom-server.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#1974 Correctly link relationship fields in test setup
  api-tests/queries/cache-hints.test.js
  api-tests/queries/limits.test.js
Labels: needs-clarification

#1972 Compute realKeys in Knex list adapter post connect
  .changeset/rich-rice-guess.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#1975 Inline KnexListAdapter.createForeignKeys()
  .changeset/early-toys-live.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#1987 Fix extendGraphQLSchema example
  README.md
  docs/guides/intro-to-graphql.md
Labels: needs-clarification

#2006 Consolidate find*() method implementations
  .changeset/fuzzy-eggs-knock.md
  api-tests/relationships/mongo/data-storage.test.js
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/keystone/lib/adapters/index.js
Labels: needs-clarification
