Repository keystonejs/keystone, pull requests merged in 2019-10, with the labels that each got.

#1713 Update queryParser to access a listAdapter
  .changeset/plenty-owls-vanish/changes.json
  .changeset/plenty-owls-vanish/changes.md
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/mongo-join-builder/examples/nested-relationship/index.js
  packages/mongo-join-builder/examples/relationship/index.js
  packages/mongo-join-builder/index.js
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/mongo-results.test.js
  packages/mongo-join-builder/tests/query-parser.test.js
  packages/mongo-join-builder/tests/utils.js
Labels: needs-clarification

#1715 Refactor internals to simplify tokenizer interfaces
  .changeset/dirty-falcons-study/changes.json
  .changeset/dirty-falcons-study/changes.md
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/lib/tokenizers/relationship-path.js
  packages/mongo-join-builder/lib/tokenizers/relationship.js
  packages/mongo-join-builder/lib/tokenizers/simple.js
  packages/mongo-join-builder/tests/relationship-path.test.js
  packages/mongo-join-builder/tests/relationship.test.js
  packages/mongo-join-builder/tests/simple.test.js
Labels: needs-clarification

#1716 Internal refactor to remove postQueryMutation
  .changeset/gorgeous-papayas-rule/changes.json
  .changeset/gorgeous-papayas-rule/changes.md
  packages/mongo-join-builder/lib/join-builder.js
  packages/mongo-join-builder/lib/tokenizers/relationship.js
  packages/mongo-join-builder/tests/join-builder.test.js
  packages/mongo-join-builder/tests/query-parser.test.js
Labels: needs-clarification

#1676 Show an error toast if there was an error creating a new item in the admin-ui
  .changeset/silver-jars-marry/changes.json
  .changeset/silver-jars-marry/changes.md
  packages/app-admin-ui/client/components/CreateItemModal.js
  packages/app-admin-ui/client/components/ToastContainer.js
  packages/app-admin-ui/client/index.js
  packages/app-admin-ui/client/util.js
Labels: admin-ui, error message

#1718 website: adjust hero container width on homepage to align with header
  website/src/components/Container.js
  website/src/pages/index.js
Labels: docs

#1722 s/import/require/
  .changeset/perfect-donuts-hope/changes.json
  .changeset/perfect-donuts-hope/changes.md
  packages/mongo-join-builder/lib/join-builder.js
Labels: needs-clarification

#1736 Add new `Location` field
  .changeset/friendly-crabs-guess/changes.json
  .changeset/friendly-crabs-guess/changes.md
  .changeset/sour-kiwis-try/changes.json
  .changeset/sour-kiwis-try/changes.md
  package.json
  packages/arch/packages/select/src/index.js
  packages/fields/README.md
  packages/fields/package.json
  packages/fields/src/index.js
  packages/fields/src/types/Location/Implementation.js
  packages/fields/src/types/Location/README.md
  packages/fields/src/types/Location/index.js
  packages/fields/src/types/Location/views/Cell.js
  packages/fields/src/types/Location/views/Controller.js
  packages/fields/src/types/Location/views/Field.js
  yarn.lock
Labels: fields

#1740 Add a global maxTotalResults limit to the Keystone object
  .changeset/weak-melons-invent/changes.json
  .changeset/weak-melons-invent/changes.md
  api-tests/queries/limits.test.js
  docs/api/create-list.md
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/List/index.js
Labels: needs-clarification

#1734 app-admin-ui: Add documentation
  .changeset/flat-lobsters-eat/changes.json
  .changeset/flat-lobsters-eat/changes.md
  packages/app-admin-ui/README.md
Labels: docs

#1735 app-next: Small documentation updates
  .changeset/tiny-adults-raise/changes.json
  .changeset/tiny-adults-raise/changes.md
  packages/app-next/README.md
Labels: docs

#1748 Fix the express-session storage configuration
  .changeset/itchy-actors-cover/changes.json
  .changeset/itchy-actors-cover/changes.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#1747 Pass more arguments to access control functions
  .changeset/empty-cougars-type/changes.json
  .changeset/empty-cougars-type/changes.md
  docs/api/access-control.md
  packages/access-control/lib/access-control.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/List/index.js
Labels: needs-clarification

#1753 Use gqlName rather than queryName
  .changeset/rotten-rabbits-divide/changes.json
  .changeset/rotten-rabbits-divide/changes.md
  packages/keystone/lib/List/index.js
Labels: needs-clarification

#1755 Update publishing guide + add backporting docs
  CONTRIBUTING.md
Labels: needs-clarification

#1729 Defer populating many-relationship fields until they're needed.
  .changeset/moody-humans-yell.md
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/adapter-mongoose/package.json
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/keystone/lib/List/index.js
  packages/keystone/lib/adapters/index.js
  packages/mongo-join-builder/lib/join-builder.js
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/package.json
Labels: needs-clarification

#1772 Add changeset for benchmarks
  .changeset/swift-insects-trade.md
Labels: needs-clarification

#1788 docs: add social media icons to header
  website/src/components/Header.js
  website/src/components/Sidebar.js
  website/src/components/SocialIconsNav.js
  website/src/components/homepage/HomepageContent.js
  website/src/components/index.js
Labels: docs

#1784 Removed adapterConnectOptions key (unused as of 144e6e86)
  .changeset/curly-paws-beg/changes.json
  .changeset/curly-paws-beg/changes.md
  .circleci/config.yml
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#1801 Add content field type on fields page
  packages/fields/README.md
Labels: needs-clarification

#1836 Fix changeset package name
  .changeset/chilled-windows-occur.md
Labels: needs-clarification

#1839 Set correct users link
  docs/guides/authentication.md
Labels: needs-clarification

#1851 Use correct namespace in changeset info
  .changeset/slimy-llamas-tell/changes.json
Labels: needs-clarification

#1849 Update dev dependencies
  .changeset/few-ducks-leave.md
  package.json
  packages/build-field-types/package.json
  packages/email/package.json
  test-projects/access-control/package.json
  test-projects/basic/package.json
  test-projects/client-validation/package.json
  test-projects/login/package.json
  test-projects/social-login/package.json
  yarn.lock
Labels: needs-clarification
