Repository keystonejs/keystone, pull requests merged in 2019-12, with the labels that each got.

#2048 Fix a test flake
  .changeset/proud-shrimps-divide.md
  api-tests/relationships/filtering/nested.test.js
Labels: needs-clarification

#2052 Clarify how to use markdown field
  packages/fields-markdown/README.md
Labels: needs-clarification

#2069 Upgrade to latest changesets cli
  docs/guides/schema.md
  package.json
  packages/app-graphql/README.md
  packages/fields-markdown/README.md
  packages/fields-wysiwyg-tinymce/README.md
  yarn.lock
Labels: needs-clarification

#2068 Update changesets for consistency before release
  .changeset/big-mangos-smoke.md
  .changeset/brown-moose-sleep.md
  .changeset/calm-apes-unite.md
  .changeset/clean-singers-reply.md
  .changeset/clever-owls-juggle.md
  .changeset/cyan-walls-attend.md
  .changeset/empty-ladybugs-brush.md
  .changeset/famous-moose-hang.md
  .changeset/funny-bats-explode.md
  .changeset/fuzzy-eggs-knock.md
  .changeset/gentle-apples-invite.md
  .changeset/gentle-keys-tease.md
  .changeset/lazy-guests-retire.md
  .changeset/metal-starfishes-exist.md
  .changeset/modern-cows-deny.md
  .changeset/popular-planets-mix.md
  .changeset/pretty-balloons-sell.md
  .changeset/pretty-parents-carry.md
  .changeset/proud-shrimps-divide.md
  .changeset/purple-news-carry.md
  .changeset/serious-experts-joke.md
  .changeset/six-fishes-give.md
  .changeset/soft-walls-arrive.md
  .changeset/thin-pianos-hunt.md
  .changeset/tough-years-wave.md
  .changeset/violet-taxis-bathe.md
  .changeset/wild-frogs-beam.md
Labels: needs-clarification

#2082 Fix broken links on mutation lifecycle page
  docs/guides/mutation-lifecycle.md
Labels: docs, needs-clarification

#2080 Fix `Cannot read property 'refetch' of undefined` when creating an item
  .changeset/selfish-geckos-clean.md
  packages/app-admin-ui/client/pages/List/index.js
Labels: admin-ui

#2085 Removed unused 'immutable' dependency
  .changeset/popular-paws-vanish.md
  package.json
  packages/fields/package.json
  yarn.lock
Labels: needs-clarification

#1986 Added S3 file adapter
  .changeset/wise-spies-tan.md
  packages/file-adapters/README.md
  packages/file-adapters/index.js
  packages/file-adapters/lib/s3.js
  packages/file-adapters/package.json
Labels: needs-clarification

#2096 Improve validation errors in Admin UI
  .changeset/six-pans-compete.md
  packages/app-admin-ui/client/components/CreateItemModal.js
  packages/app-admin-ui/client/pages/Item/index.js
  packages/app-admin-ui/client/util.js
Labels: admin-ui

#2102 Clarify that DateTimeUTC is a separate package
  packages/fields-datetime-utc/README.md
Labels: needs-clarification

#2106 Remove isSetup logic
  .changeset/lazy-ladybugs-call.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#2125 Add missing changeset for #2123
  .changeset/nine-ravens-leave.md
Labels: needs-clarification

#2128 Small updates to custom mutations page
  docs/guides/custom-mutations.md
Labels: docs

#2149 Upgrade all eslint dependencies
  .changeset/rich-apes-kneel.md
  .eslintrc.js
  CONTRIBUTING.md
  README.md
  demo-projects/meetup/package.json
  package.json
  yarn.lock
Labels: needs-clarification
