Repository keystonejs/keystone, pull requests merged in 2019-09, with the labels that each got.

#1560 Move Session handling logic from graphQL app to keystone package
  .changeset/kind-gorillas-work/changes.json
  .changeset/kind-gorillas-work/changes.md
  packages/app-graphql/index.js
  packages/app-graphql/lib/apolloServer.js
  packages/app-graphql/package.json
  packages/auth-passport/lib/Passport.js
  packages/keystone/lib/Keystone/index.js
  packages/test-utils/lib/test-utils.js
  test-projects/social-login/index.js
  test-projects/social-login/server.js
Labels: auth

#1566 Remove `hostURL` and `apiPath` options from `PassportAuthStrategy` constructor
  .changeset/shy-horses-repair/changes.json
  .changeset/shy-horses-repair/changes.md
  package.json
  packages/auth-passport/README.md
  packages/auth-passport/lib/Passport.js
  packages/auth-passport/package.json
  test-projects/social-login/config.js
  test-projects/social-login/index.js
  test-projects/social-login/server.js
  yarn.lock
Labels: auth

#1592 Remove skipAccessControl from keystone.getTypeDefs()
  .changeset/gorgeous-papayas-fry/changes.json
  .changeset/gorgeous-papayas-fry/changes.md
  docs/quick-start/getting-started.md
  packages/fields/src/Implementation.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/List/index.js
Labels: breaking change

#1662 Show correct pluralised value in admin-ui sidebar nav
  .changeset/funny-pumas-heal/changes.json
  .changeset/funny-pumas-heal/changes.md
  packages/app-admin-ui/client/components/Nav/index.js
Labels: admin-ui

#1664 Add support for alpha channel in color field
  .changeset/nice-grapes-compare/changes.json
  .changeset/nice-grapes-compare/changes.md
  packages/fields/src/types/Color/README.md
  packages/fields/src/types/Color/views/Cell.js
  packages/fields/src/types/Color/views/Field.js
Labels: admin-ui, fields

#1680 Make keystone.executeQuery() backwards compatible
  .changeset/light-beers-fetch/changes.json
  .changeset/light-beers-fetch/changes.md
  packages/keystone/lib/Keystone/index.js
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#1687 Add schemaName and schemaNames parameters to setupServer()
  .changeset/ninety-boats-chew/changes.json
  .changeset/ninety-boats-chew/changes.md
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#1692 Replace alpha symbol on website with alpha version number
  website/src/components/Header.js
  website/src/components/homepage/HomepageContent.js
Labels: docs

#1689 Rename Keystone to KeystoneJS in docs where possible
  .changeset/hot-laws-travel/changes.json
  .changeset/hot-laws-travel/changes.md
  README.md
  demo-projects/blog/README.md
  demo-projects/todo/README.md
  docs/api/authentication.md
  docs/api/create-list.md
  docs/api/validation.md
  docs/guides/access-control.md
  docs/guides/authentication.md
  docs/guides/custom-field-types.md
  docs/guides/custom-server.md
  docs/guides/hooks.md
  docs/guides/initial-data.md
  docs/guides/intro-to-graphql.md
  docs/guides/mutation-lifecycle.md
  docs/guides/new-project.md
  docs/guides/performance.md
  docs/guides/relationships.md
  docs/guides/schema.md
  docs/quick-start/adapters.md
  docs/quick-start/getting-started.md
  packages/adapter-knex/README.md
  packages/adapter-mongoose/README.md
  packages/apollo-helpers/README.md
  packages/app-graphql-playground/README.md
  packages/app-graphql/README.md
  packages/app-schema-router/README.md
  packages/app-static/README.md
  packages/auth-password/README.md
  packages/fields/README.md
  packages/fields/src/types/CalendarDay/README.md
  packages/fields/src/types/Checkbox/README.md
  packages/fields/src/types/DateTime/README.md
  packages/fields/src/types/Slug/README.md
  packages/file-adapters/README.md
  packages/keystone/README.md
  packages/keystone/lib/adapters/README.md
  packages/session/README.md
  packages/test-utils/README.md
  test-projects/basic/custom-fields/Stars/README.md
Labels: docs

#1707 Add a compose() function to utils
  .changeset/nine-moons-collect/changes.json
  .changeset/nine-moons-collect/changes.md
  .changeset/rotten-seals-begin/changes.json
  .changeset/rotten-seals-begin/changes.md
  packages/keystone/lib/Keystone/index.js
  packages/mongo-join-builder/lib/join-builder.js
  packages/utils/src/index.js
Labels: needs-clarification

#1706 Internal refactor to decompose joinBuilder()
  .changeset/lovely-files-return/changes.json
  .changeset/lovely-files-return/changes.md
  packages/mongo-join-builder/lib/index.js
  packages/mongo-join-builder/lib/join-builder.js
  packages/mongo-join-builder/tests/join-builder.test.js
Labels: needs-clarification

#1709 Move tokenizers into mongo-join-builder package.
  .changeset/spicy-dodos-know/changes.json
  .changeset/spicy-dodos-know/changes.md
  .changeset/witty-schools-kneel/changes.json
  .changeset/witty-schools-kneel/changes.md
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/adapter-mongoose/package.json
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/mongo-join-builder/index.js
  packages/mongo-join-builder/lib/tokenizers/relationship-path.js
  packages/mongo-join-builder/lib/tokenizers/relationship.js
  packages/mongo-join-builder/lib/tokenizers/simple.js
  packages/mongo-join-builder/package.json
  packages/mongo-join-builder/tests/relationship-path.test.js
  packages/mongo-join-builder/tests/relationship.test.js
  packages/mongo-join-builder/tests/simple.test.js
Labels: needs-clarification

#1711 Remove the mongoJoinBuilder() function
  .changeset/odd-parrots-develop/changes.json
  .changeset/odd-parrots-develop/changes.md
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/mongo-join-builder/examples/nested-relationship/index.js
  packages/mongo-join-builder/examples/relationship/index.js
  packages/mongo-join-builder/index.js
  packages/mongo-join-builder/lib/index.js
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/mongo-results.test.js
Labels: needs-clarification

#1710 Increase specificity of query-parser tests
  packages/mongo-join-builder/tests/query-parser.test.js
Labels: needs-clarification
