Repository keystonejs/keystone, pull requests merged in 2020-03, with the labels that each got.

#2436 Provider 3/n: Add a CustomProvider class
  .changeset/rotten-ants-pump.md
  api-tests/extend-graphql-schema/extend-graphql-schema.test.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/providers/custom.js
  packages/keystone/lib/providers/index.js
  packages/keystone/tests/Keystone.test.js
Labels: needs-clarification

#2456 Providers 5/n: Auth access control
  .changeset/lemon-pears-develop.md
  .changeset/odd-rocks-serve.md
  packages/access-control/index.js
  packages/access-control/lib/access-control.js
  packages/access-control/tests/access-control.test.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/List/index.js
  packages/keystone/tests/List.test.js
Labels: needs-clarification

#2459 Add _executeOperation method to Keystone class
  .changeset/eleven-experts-fetch.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#2467 Remove undocumented DEBUG_GRAPHQL_SCHEMAS
  .changeset/smart-wolves-repair.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#2485 changes to changesets
  .changeset/dry-buttons-build.md
  .changeset/flat-worms-wonder.md
  .changeset/thin-feet-change.md
Labels: needs-clarification

#2504 Move tutorials into their own section
  .changeset/dirty-laws-itch.md
  CONTRIBUTING.md
  README.md
  docs/quick-start/README.md
  docs/tutorials/add-lists.md
  docs/tutorials/index.md
  docs/tutorials/initial-data.md
  docs/tutorials/new-project.md
  docs/tutorials/relationships.md
  packages/arch/packages/color-utils/CHANGELOG.md
  packages/fields-mongoid/README.md
  packages/fields-wysiwyg-tinymce/README.md
  website/gatsby-node.js
  website/src/components/Header.js
Labels: docs, needs-clarification

#2513 Clean up quick start docs
  docs/quick-start/README.md
  docs/quick-start/adapters.md
  packages/fields-wysiwyg-tinymce/README.md
Labels: docs, needs-clarification

#2514 Update tutorial docs
  docs/tutorials/add-lists.md
  docs/tutorials/initial-data.md
  docs/tutorials/new-project.md
  docs/tutorials/relationships.md
Labels: docs, needs-clarification

#2524 Create new upcase util
  .changeset/big-hats-lie.md
  packages/app-admin-ui/client/pages/Signin.js
  packages/keystone/lib/List/index.js
  packages/keystone/lib/providers/listAuth.js
  packages/utils/src/index.js
  packages/utils/tests/utils.test.js
Labels: needs-clarification

#2525 Refactored `matchFilter` to use named args (via an object)
  .changeset/little-geese-hunt.md
  packages/fields/src/types/CalendarDay/filterTests.js
  packages/fields/src/types/Checkbox/filterTests.js
  packages/fields/src/types/DateTime/filterTests.js
  packages/fields/src/types/Decimal/filterTests.js
  packages/fields/src/types/Float/filterTests.js
  packages/fields/src/types/Integer/filterTests.js
  packages/fields/src/types/Password/filterTests.js
  packages/fields/src/types/Select/filterTests.js
  packages/fields/src/types/Text/filterTests.js
  packages/fields/src/types/Uuid/filterTests.js
  packages/fields/tests/idFilterTests.js
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#2527 Updated to latest version of globby for discovering test files to run.
  .changeset/plenty-wasps-poke.md
  api-tests/fields.test.js
  api-tests/package.json
  api-tests/required.test.js
  packages/build-field-types/package.json
  packages/keystone/package.json
  yarn.lock
Labels: needs-clarification

#2530 Less typo
  .changeset/plenty-wasps-poke.md
Labels: needs-clarification

#2533 website: Fix packages page
  website/src/templates/packages.js
Labels: docs

#2531 Fixed a minor typo
  .changeset/curvy-moons-agree.md
  demo-projects/meetup/site/components/auth/signup.js
  packages/app-graphql/lib/graphqlErrors.js
Labels: needs-clarification

#2528 website: Remove duplicate components/utilities
  website/src/pages/404.js
  website/src/pages/index.js
  website/src/templates/docs.js
  website/src/templates/index.js
  website/src/templates/layout.js
  website/src/templates/packages.js
  website/src/utils/case.js
Labels: docs

#2536 Break out middleware preparation into separate method
  .changeset/nervous-eels-fold.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#2537 Introduce CRUD testing framework to fix bug in Decimal field
  .changeset/funny-pugs-kiss.md
  api-tests/fields.test.js
  api-tests/required.test.js
  package.json
  packages/fields/package.json
  packages/fields/src/types/CalendarDay/test-fixtures.js
  packages/fields/src/types/Checkbox/test-fixtures.js
  packages/fields/src/types/DateTime/test-fixtures.js
  packages/fields/src/types/Decimal/Implementation.js
  packages/fields/src/types/Decimal/filterTests.js
  packages/fields/src/types/Decimal/test-fixtures.js
  packages/fields/src/types/Float/test-fixtures.js
  packages/fields/src/types/Integer/test-fixtures.js
  packages/fields/src/types/Password/test-fixtures.js
  packages/fields/src/types/Select/test-fixtures.js
  packages/fields/src/types/Text/test-fixtures.js
  packages/fields/src/types/Uuid/test-fixtures.js
  packages/fields/tests/test-fixtures.js
Labels: needs-clarification

#2547 website: Add sitemap
  website/gatsby-config.js
  website/package.json
  yarn.lock
Labels: docs

#2549 Remove useless existingItem field from defaultValue field function
  .changeset/plenty-donkeys-draw.md
  api-tests/default-value/defaults.test.js
  packages/fields/README.md
  packages/fields/src/Implementation.js
  packages/fields/tests/Implementation.test.js
  packages/keystone/lib/List/index.js
Labels: hooks

#2543 Add rels data structure to adapters
  .changeset/orange-singers-guess.md
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/adapters/index.js
Labels: needs-clarification

#2544 Remove the prepareFieldAdapter method
  .changeset/twelve-clouds-fetch.md
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/keystone/lib/adapters/index.js
Labels: needs-clarification

#2548 website: Add docsearch classes
  packages/arch/docs/package.json
  website/package.json
  website/src/components/SidebarNav.js
  website/src/templates/docs.js
  website/src/templates/index.js
  website/src/templates/layout.js
  website/src/templates/packages.js
  yarn.lock
Labels: docs, needs-clarification

#2492 Knex adapter internal updates
  .changeset/fast-windows-kneel.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#2546 website: Add Algolia Docsearch
  demo-projects/blog/package.json
  demo-projects/meetup/package.json
  package.json
  website/gatsby-config.js
  website/package.json
  website/src/components/Footer.js
  website/src/components/Header.js
  website/src/components/Search.js
  website/src/components/Sidebar.js
  website/src/components/SidebarNav.js
  website/src/html.js
  website/src/utils/algolia-styles.js
  website/src/utils/async-load-search.js
  website/src/utils/search.js
  yarn.lock
Labels: docs

#2529 Session manager ideas
  .changeset/smooth-doors-juggle.md
  packages/auth-passport/lib/Passport.js
  packages/keystone/lib/Keystone/index.js
  packages/session/index.js
  packages/session/lib/session.js
Labels: needs-clarification
