Repository keystonejs/keystone, pull requests merged in 2020-06, with the labels that each got.

#3074 Try to fix CI timeouts
  api-tests/access-control/authed.test.js
  api-tests/access-control/not-authed.test.js
  api-tests/access-control/schema.test.js
Labels: needs-clarification

#2817 Admin UI: custom success toast UI hook
  .changeset/strong-candles-film.md
  packages/app-admin-ui/README.md
  packages/app-admin-ui/client/pages/Item/index.js
  packages/app-admin-ui/client/util.js
Labels: merge conflict

#3077 Catch error with multicheck when value is null
  .changeset/good-laws-rhyme.md
  demo-projects/custom-fields/fields/MultiCheck/views/Cell.js
Labels: needs-clarification

#3081 File/Implementation.js: remove useless code
  .changeset/fresh-hats-begin.md
  packages/fields/src/types/File/Implementation.js
Labels: needs-clarification

#3082 Refactor customToast
  .changeset/chilled-eagles-compete.md
  .changeset/real-pots-joke.md
  .changeset/strong-candles-film.md
  docs/guides/hooks.md
  packages/app-admin-ui/README.md
  packages/app-admin-ui/client/pages/Item/index.js
  packages/app-admin-ui/client/util.js
Labels: needs-clarification

#3095 Provide all resolver info to custom access control functions
  .changeset/beige-wombats-eat.md
  docs/api/access-control.md
  packages/access-control/lib/access-control.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/providers/custom.js
Labels: needs-clarification

#3106 Fix some wording issues
  website/src/components/homepage/SectionFeatures.js
Labels: needs-clarification

#3109 fix typo
  README.md
Labels: needs-clarification

#3116 Fix code in access control docs
  CONTRIBUTING.md
  README.md
  docs/api/access-control.md
Labels: needs-clarification

#3122 Add note about relationship fields in hooks
  docs/api/hooks.md
Labels: needs-clarification

#3002 Add dateFrom, dateTo validation to CalendarDay
  .changeset/spotty-planes-peel.md
  api-tests/CalendarDay.test.js
  api-tests/package.json
  demo-projects/blog/package.json
  demo-projects/blog/schema.js
  demo-projects/meetup/package.json
  demo-projects/todo/index.js
  packages/arch/packages/day-picker/package.json
  packages/fields/package.json
  packages/fields/src/types/CalendarDay/Implementation.js
  packages/fields/src/types/CalendarDay/Implementation.test.js
  packages/fields/src/types/CalendarDay/README.md
  packages/fields/src/types/CalendarDay/views/Controller.js
  test-projects/basic/index.js
  test-projects/basic/package.json
  test-projects/client-validation/package.json
  yarn.lock
Labels: hot stuff

#3144 Fix
  demo-projects/todo/index.js
Labels: needs-clarification

#3157 Update docs which reference dumpSchema
  docs/guides/performance.md
  packages/keystone/README.md
Labels: needs-clarification

#3156 Make admin UI build correctly with PNPM
  .changeset/shaggy-dolphins-fold.md
  packages/app-admin-ui/server/getWebpackConfig.js
Labels: needs-clarification

#3159 Use keystone.executeGraphQL in test-utils
  .changeset/tiny-bikes-join.md
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#3160 Use context.executeGraphQL in singleton plugin
  .changeset/warm-toes-doubt.md
  packages/list-plugins/lib/limiting/singleton.js
Labels: needs-clarification

#3161 Use keystone.executeGraphQL in starter project
  .changeset/swift-baboons-cough.md
  packages/create-keystone-app/example-projects/starter/initial-data.js
Labels: needs-clarification

#3162 Use context.executeGraphQL in meetup demo
  .changeset/odd-penguins-divide.md
  demo-projects/meetup/schema.js
Labels: needs-clarification

#3163 Use keystone.executeGraphQL in Passport package
  .changeset/hip-pears-visit.md
  packages/auth-passport/lib/Passport.js
Labels: needs-clarification

#3165 Add deprecation warnings for old server-side query mechanisms
  .changeset/large-falcons-clap.md
  docs/api/hooks.md
  docs/guides/intro-to-graphql.md
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/lib/providers/custom.js
Labels: needs-clarification

#3167 Use context.executeGraphQL in Slug field type
  .changeset/wicked-books-knock.md
  packages/fields/src/types/Slug/Implementation.js
Labels: needs-clarification

#3168 Fix bug from previous PR
  demo-projects/meetup/schema.js
Labels: needs-clarification

#3193 Fix executeGraphQL bug
  .changeset/hot-pigs-hear.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#3211 s/sown/shown
  docs/guides/authentication.md
Labels: needs-clarification
