Repository keystonejs/keystone, pull requests merged in 2020-01, with the labels that each got.

#2181 Add missing )
  packages/file-adapters/README.md
Labels: needs-clarification

#2189 Upgrade prettier to 1.19.1
  .changeset/brown-onions-hang.md
  api-tests/relationships/crud/many-to-many-no-ref.test.js
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/crud/one-to-many-no-ref.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
  demo-projects/blog/schema.js
  demo-projects/meetup/site/pages/profile.js
  docs/guides/schema.md
  package.json
  packages/adapter-knex/lib/adapter-knex.js
  packages/apollo-helpers/src/index.js
  packages/build-field-types/src/fix.js
  packages/fields/src/types/Relationship/nested-mutations.js
  packages/fields/src/types/Select/Implementation.js
  packages/file-adapters/README.md
  packages/keystone/lib/List/index.js
  packages/keystone/tests/Keystone.test.js
  packages/keystone/tests/relationship-utils.test.js
  packages/mongo-join-builder/README.md
  packages/mongo-join-builder/examples/database.js
  packages/mongo-join-builder/lib/query-parser.js
  packages/utils/src/index.js
  packages/utils/tests/utils.test.js
  test-projects/access-control/data.js
  test-projects/basic/cypress/integration/load-users-list_spec.js
  test-projects/basic/cypress/integration/local-file-upload_spec.js
  test-projects/basic/index.js
  test-projects/social-login/index.js
  website/src/components/Search.js
  yarn.lock
Labels: needs-clarification

#2190 Upgrade knex dependencies
  .changeset/cool-doors-notice.md
  package.json
  packages/adapter-knex/package.json
  yarn.lock
Labels: needs-clarification

#2191 Upgrade mongoose and mongodb dependencies.
  .changeset/dull-toes-impress.md
  package.json
  packages/adapter-mongoose/package.json
  packages/fields/package.json
  packages/mongo-join-builder/package.json
  yarn.lock
Labels: needs-clarification

#2192 Clean up changelogs before publishing packages
  .changeset/brave-chairs-mix.md
  .changeset/brown-parents-act.md
  .changeset/calm-ants-flash.md
  .changeset/giant-wasps-call.md
  .changeset/hungry-crabs-sell.md
  .changeset/itchy-books-explode.md
  .changeset/rich-apes-kneel.md
Labels: needs-clarification

#2198 UX updates to admin ui search
  .changeset/chatty-walls-give.md
  packages/app-admin-ui/client/pages/List/Search.js
  packages/app-admin-ui/client/pages/List/dataHooks.js
Labels: admin-ui

#2202 Fix apps which don't define build()
  .changeset/dull-taxis-relax.md
  docs/guides/apps.md
  docs/guides/new-project.md
  docs/guides/production.md
  packages/keystone/bin/commands/build.js
  yarn.lock
Labels: needs-clarification

#2204 Fix website meta tags
  website/src/components/SiteMeta.js
Labels: docs

#2223 Correct spelling mistake
  docs/guides/custom-mutations.md
Labels: needs-clarification

#2215 Update schema.md
  docs/guides/schema.md
Labels: needs-clarification

#2222 Fix spelling mistake
  docs/guides/access-control.md
Labels: needs-clarification

#2219 Capitalize GraphQL
  docs/guides/performance.md
Labels: needs-clarification

#2218 Update intro-to-graphql.md
  docs/guides/intro-to-graphql.md
Labels: needs-clarification

#2232 Same PR without en-US corrections
  docs/guides/mutation-lifecycle.md
Labels: needs-clarification

#2229 Simplify parsing with a separate modifier tokenizer
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/lib/tokenizers.js
  packages/mongo-join-builder/tests/relationship-path.test.js
  packages/mongo-join-builder/tests/simple.test.js
Labels: needs-clarification

#2233 Always run linting tests even when PRs skip other tests
  .circleci/config.yml
Labels: needs-clarification

#2247 Simplify mongo queries
  .changeset/strange-toes-mate.md
  CONTRIBUTING.md
  README.md
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/mongo-join-builder/lib/join-builder.js
  packages/mongo-join-builder/lib/tokenizers.js
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/join-builder.test.js
  packages/mongo-join-builder/tests/query-parser.test.js
  packages/mongo-join-builder/tests/relationship.test.js
Labels: needs-clarification

#2248 Grammar
  packages/fields/src/types/DateTime/README.md
Labels: needs-clarification

#2251 Use a $project pipeline step, rather than post-processing results.
  .changeset/cool-bees-joke.md
  .changeset/olive-mails-do.md
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/adapter-mongoose/package.json
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/fields/src/types/DateTime/README.md
  packages/file-adapters/README.md
  packages/mongo-join-builder/examples/nested-relationship/index.js
  packages/mongo-join-builder/examples/relationship/index.js
  packages/mongo-join-builder/index.js
  packages/mongo-join-builder/lib/join-builder.js
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/package.json
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/join-builder.test.js
  packages/mongo-join-builder/tests/mongo-results.test.js
  packages/mongo-join-builder/tests/query-parser.test.js
  yarn.lock
Labels: needs-clarification

#2252 Fixed Typo in ReadMe
  packages/create-keystone-app/README.md
Labels: needs-clarification

#2264 admin-ui: Fix bug where the search input on the List page would gain focus when the user pressed SHIFT
  .changeset/pink-dolls-arrive.md
  packages/app-admin-ui/client/pages/List/Search.js
Labels: admin-ui

#2267 Remove unused query arg from relationship tokenizer
  .changeset/eleven-phones-happen.md
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/lib/tokenizers.js
  packages/mongo-join-builder/tests/relationship.test.js
Labels: needs-clarification

#2268 Clean up join builder tests in prep for relationship changes
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/join-builder.test.js
  packages/mongo-join-builder/tests/mongo-results.test.js
  packages/mongo-join-builder/tests/query-parser.test.js
Labels: needs-clarification

#2269 Add a check for invalid relationship configurations
  .changeset/swift-lobsters-mate.md
  .changeset/unlucky-swans-deliver.md
  packages/fields/src/types/CloudinaryImage/ImageBlock.js
  packages/fields/src/types/OEmbed/OEmbedBlock.js
  packages/fields/src/types/Unsplash/UnsplashBlock.js
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#2309 Clean up changelogs prior to release
  .changeset/five-apples-thank.md
  .changeset/silent-horses-tie.md
  .changeset/strong-dolphins-work.md
  .changeset/tricky-shoes-hang.md
  .changeset/twenty-baboons-cheat.md
  .changeset/wet-bottles-hear.md
Labels: needs-clarification

#2310 Add a missing dependency require to build packages
  .changeset/friendly-geese-judge.md
  packages/app-admin-ui/package.json
Labels: needs-clarification
