Repository keystonejs/keystone, pull requests merged in 2020-11, with the labels that each got.

#4106 Remove `"private": true` from new interfaces
  .changeset/little-moons-rest.md
  design-system/packages/button/package.json
  design-system/packages/core/package.json
  design-system/packages/fields/package.json
  design-system/packages/icons/package.json
  design-system/packages/loading/package.json
  design-system/packages/modals/package.json
  design-system/packages/notice/package.json
  design-system/packages/options/package.json
  design-system/packages/pill/package.json
  design-system/packages/popover/package.json
  design-system/packages/segmented-control/package.json
  design-system/packages/toast/package.json
  design-system/packages/tooltip/package.json
  packages-next/admin-ui/package.json
  packages-next/auth/package.json
  packages-next/fields/package.json
  packages-next/keystone/package.json
  packages-next/session-store-redis/package.json
  packages-next/types/package.json
Labels: new interfaces

#4109 Appease typechecker
  .github/workflows/tests.yml
Labels: review me

#4110 Make view paths relative in generated code in new interfaces
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/keystone/src/lib/generateAdminUI.ts
Labels: new interfaces

#4107 New interfaces auth fixes
  examples-next/basic/.keystone/schema-types.ts
  packages-next/TODO.md
  packages-next/auth/TODO.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/index.ts
  packages-next/auth/src/lib/attemptAuthentication.ts
  packages-next/auth/src/lib/getErrorMessage.ts
  packages-next/auth/src/lib/redeemAuthToken.ts
  packages-next/auth/src/lib/updateAuthToken.ts
  packages-next/auth/src/lib/updateItemSecret.ts
  packages-next/auth/src/lib/validateAuthToken.ts
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/auth/src/pages/SigninPage.tsx
  packages-next/auth/src/templates/signin.ts
  packages-next/auth/src/types.ts
Labels: new interfaces

#4108 Custom view merging in new interfaces
  examples-next/basic/admin/fieldViews/Content.tsx
  examples-next/basic/schema.ts
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/types/src/admin-meta.ts
Labels: new interfaces

#4127 New interfaces item page refactoring
  packages-next/admin-ui/src/pages/ItemPage/Fields.tsx
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
  packages-next/admin-ui/src/pages/ItemPage/useInvalidFields.ts
Labels: new interfaces

#4128 Adding Readme to examples-next
  examples-next/README.md
Labels: new interfaces

#4137 Add missing options to types in field options in new interfaces
  .changeset/thin-months-destroy.md
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/checkbox/index.ts
  packages-next/fields/src/types/integer/index.ts
  packages-next/fields/src/types/mongoId/index.ts
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/select/index.ts
  packages-next/fields/src/types/text/index.ts
Labels: new interfaces

#4132 Add displayMode: 'cards' to relationship field in new interfaces
  .changeset/brave-games-lay.md
  .changeset/khaki-avocados-grow.md
  .changeset/large-flowers-mix.md
  .changeset/silly-apes-exercise.md
  .changeset/young-wolves-know.md
  examples-next/basic/.keystone/schema-types.ts
  examples-next/basic/schema.ts
  packages-next/admin-ui-utils/package.json
  packages-next/admin-ui-utils/src/Fields.tsx
  packages-next/admin-ui-utils/src/dataGetter.ts
  packages-next/admin-ui-utils/src/getRootGraphQLFieldsFromFieldController.ts
  packages-next/admin-ui-utils/src/index.ts
  packages-next/admin-ui-utils/src/item-form.ts
  packages-next/admin-ui-utils/src/serialization.tsx
  packages-next/admin-ui-utils/src/useInvalidFields.ts
  packages-next/admin-ui/package.json
  packages-next/admin-ui/pages/HomePage/package.json
  packages-next/admin-ui/pages/ItemPage/package.json
  packages-next/admin-ui/pages/ListPage/package.json
  packages-next/admin-ui/pages/NoAccessPage/package.json
  packages-next/admin-ui/src/index.tsx
  packages-next/admin-ui/src/pages/HomePage/index.tsx
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/NoAccessPage/index.tsx
  packages-next/admin-ui/src/templates/home.ts
  packages-next/admin-ui/src/templates/item.tsx
  packages-next/admin-ui/src/templates/list.tsx
  packages-next/admin-ui/src/templates/no-access.ts
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/auth/src/templates/init.ts
  packages-next/fields/TODO.md
  packages-next/fields/package.json
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/integer/views/index.tsx
  packages-next/fields/src/types/mongoId/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/relationship/views/RelationshipSelect.tsx
  packages-next/fields/src/types/relationship/views/cards/InlineCreate.tsx
  packages-next/fields/src/types/relationship/views/cards/InlineEdit.tsx
  packages-next/fields/src/types/relationship/views/cards/index.tsx
  packages-next/fields/src/types/relationship/views/cards/useItemState.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/fields/src/types/select/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
  packages-next/fields/src/types/virtual/views/index.tsx
  packages-next/types/src/admin-meta.ts
Labels: new interfaces

#4145 Fix issues with cards displayMode with to-one relationships
  examples-next/basic/schema.ts
  packages-next/fields/src/types/relationship/views/cards/index.tsx
  packages-next/fields/src/types/relationship/views/cards/useItemState.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: needs-clarification

#4138 Cloudinary image field for new interfaces
  .changeset/breezy-seals-tell.md
  .changeset/large-bulldogs-punch.md
  .changeset/mighty-badgers-move.md
  .changeset/moody-flowers-wave.md
  examples-next/basic/schema.ts
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/context.tsx
  packages-next/cloudinary/package.json
  packages-next/cloudinary/src/index.ts
  packages-next/cloudinary/src/views/Field.tsx
  packages-next/cloudinary/src/views/index.tsx
  packages-next/cloudinary/views/package.json
  packages-next/keystone/src/scripts/schema-type-printer.tsx
  packages-next/types/src/admin-meta.ts
  yarn.lock
Labels: new interfaces

#4146 Small fixes with buttons in new interfaces
  .changeset/dirty-mayflies-switch.md
  .changeset/lemon-seals-sneeze.md
  packages-next/admin-ui/src/pages/HomePage/index.tsx
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/auth/src/templates/init.ts
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: new interfaces

#4147 Rename inlineLink to inlineConnect in relationship field config
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: new interfaces

#4160 Show a neutral button on the Item form when there are no changes to save
  .changeset/wise-socks-join.md
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
Labels: new interfaces

#4162 Adding new color palette
  .changeset/mighty-sheep-compare.md
  design-system/packages/core/src/themes/colors.ts
  design-system/packages/core/src/themes/colors_old.ts
  design-system/packages/core/src/themes/default.ts
Labels: new interfaces

#4159 Remove outline button style
  .changeset/honest-jeans-battle.md
  design-system/packages/button/src/hooks/button.ts
  design-system/packages/notice/src/hooks/button.ts
Labels: new interfaces

#4165 Run yarn format
  design-system/packages/button/CHANGELOG.md
  design-system/packages/core/CHANGELOG.md
  design-system/packages/fields/CHANGELOG.md
  design-system/packages/icons/CHANGELOG.md
  design-system/packages/loading/CHANGELOG.md
  design-system/packages/modals/CHANGELOG.md
  design-system/packages/notice/CHANGELOG.md
  design-system/packages/options/CHANGELOG.md
  design-system/packages/pill/CHANGELOG.md
  design-system/packages/popover/CHANGELOG.md
  design-system/packages/segmented-control/CHANGELOG.md
  design-system/packages/toast/CHANGELOG.md
  design-system/packages/tooltip/CHANGELOG.md
  design-system/website/CHANGELOG.md
  docs/guides/custom-server.md
  packages-next/admin-ui-utils/CHANGELOG.md
  packages-next/cloudinary/CHANGELOG.md
  packages-next/session-store-redis/CHANGELOG.md
Labels: review me

#4179 Fix defaultValue types for autoIncrement and integer fields
  .changeset/poor-pants-tan.md
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/integer/index.ts
Labels: new interfaces

#4181 Fix fields with read access control statically false breaking the ite…
  .changeset/lovely-moose-mix.md
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
Labels: new interfaces

#4182 Fix item form not being updated with new values when no errors are re…
  .changeset/itchy-gifts-smash.md
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
Labels: new interfaces

#4183 Always load the session item in withItemData
  .changeset/beige-elephants-deny.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces

#4185 Fixed field defaultValue types for new fields package
  .changeset/pink-fishes-hunt.md
  packages-next/fields/TODO.md
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/checkbox/index.ts
  packages-next/fields/src/types/integer/index.ts
  packages-next/fields/src/types/mongoId/index.ts
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/select/index.ts
  packages-next/fields/src/types/text/index.ts
  packages-next/fields/src/types/timestamp/index.ts
  packages-next/types/src/index.ts
  packages-next/types/src/schema/hooks.ts
Labels: new interfaces

#4186 Improving the appearance of readonly fields in the Admin UI
  .changeset/angry-goats-begin.md
  design-system/packages/core/src/themes/default.ts
  design-system/packages/fields/src/hooks/inputs.ts
  packages-next/fields/src/types/integer/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
Labels: new interfaces

#4187 Improve readonly relationship views
  .changeset/calm-planes-wash.md
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: needs-clarification

#4189 Add new todo example (WIP)
  examples-next/TODO.md
  examples-next/todo/keystone.ts
  examples-next/todo/package.json
  examples-next/todo/schema.ts
Labels: new interfaces

#4195 Fix create item modals staying open after creating when on the item page
  .changeset/empty-shirts-nail.md
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
Labels: new interfaces

#4196 Fix Stack adding an extra gap when the first child is not a valid ele…
  .changeset/chatty-buses-compete.md
  design-system/packages/core/src/components/Stack.tsx
Labels: new interfaces

#4198 Fix fields on item page flicking between new value and old value when…
  .changeset/smart-apes-sniff.md
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
Labels: new interfaces

#4197 Improve field UI when fields have `itemView: { fieldMode: 'read'}`
  .changeset/cyan-owls-lay.md
  packages-next/cloudinary/src/views/Field.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/relationship/views/cards/index.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
Labels: new interfaces

#4200 Rename CRUD API
  .changeset/fast-numbers-eat.md
  examples-next/basic/schema.ts
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/keystone/src/lib/itemAPI.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#4201 New internal graphql api
  .changeset/metal-turtles-carry.md
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#4203 Fixed Admin UI schema extension usage of renamed crud API
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
Labels: new interfaces

#4204 Fix Select menu cropping in create item drawer
  .changeset/gold-poets-fetch.md
  design-system/packages/fields/src/Select.tsx
Labels: new interfaces

#4205 Update initialColumns in todo project
  examples-next/todo/schema.ts
Labels: new interfaces

#4206 Fixing menu cropping in Drawers for multi select
  design-system/packages/fields/src/Select.tsx
Labels: new interfaces

#4207 Improve field cell components
  .changeset/four-clouds-fail.md
  packages-next/admin-ui/src/components/CellContainer.tsx
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/mongoId/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/relationship/views/RelationshipSelect.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/fields/src/types/select/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
  packages-next/fields/src/types/virtual/views/index.tsx
Labels: new interfaces

#4209 Add the missing field.label type
  packages-next/types/src/index.ts
Labels: new interfaces

#4210 Fix the default textarea width
  design-system/packages/fields/src/TextArea.tsx
Labels: new interfaces

#4212 Rename KeystoneItemAPI to KeystoneListsAPI
  .changeset/chilly-hounds-smell.md
  examples-next/basic/schema.ts
  packages-next/keystone/src/lib/itemAPI.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#4214 Fixing admin access in the auth example
  examples-next/auth/schema.ts
Labels: new interfaces

#4213 Adding new eCommerce example app
  examples-next/ecommerce/README.md
  examples-next/ecommerce/keystone.ts
  examples-next/ecommerce/package.json
  examples-next/ecommerce/sample.env
  examples-next/ecommerce/schema.ts
  examples-next/ecommerce/types.ts
Labels: new interfaces

#4225 Fix dropdown in nav in Firefox
  packages-next/admin-ui/src/components/Navigation.tsx
Labels: new interfaces

#4224 Fix lazy admin meta being in loading state in Safari after restarting…
  .changeset/rich-lamps-enjoy.md
  packages-next/admin-ui/src/context.tsx
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/admin-ui/src/utils/useLazyMetadata.tsx
Labels: new interfaces

#4229 Fix margin between toolbar and form in Create modal
  design-system/packages/modals/src/Drawer.tsx
Labels: new interfaces

#4230 Add Cross-Origin Resource Support to the dev server
  .changeset/short-needles-cry.md
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/createAdminUIServer.ts
Labels: new interfaces

#4231 Fixed the session permissions loading in the eCommerce example
  examples-next/ecommerce/keystone.ts
Labels: new interfaces

#4239 Add support for onConnect in new interfaces
  .changeset/curly-comics-work.md
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4242 Remove name field from KeystoneConfig
  .changeset/tall-jars-sparkle.md
  examples-next/auth/keystone.ts
  examples-next/basic/keystone.ts
  examples-next/ecommerce/keystone.ts
  examples-next/todo/keystone.ts
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4238 Add getBackingTypes() to Implementation
  .changeset/healthy-chefs-smash.md
  .changeset/hip-humans-jam.md
  .changeset/thick-monkeys-camp.md
  packages-next/cloudinary/src/index.ts
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/checkbox/index.ts
  packages-next/fields/src/types/integer/index.ts
  packages-next/fields/src/types/mongoId/index.ts
  packages-next/fields/src/types/password/index.ts
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/select/index.ts
  packages-next/fields/src/types/text/index.ts
  packages-next/fields/src/types/timestamp/index.ts
  packages-next/fields/src/types/virtual/index.ts
  packages-next/keystone/src/scripts/schema-type-printer.tsx
  packages-next/types/src/index.ts
  packages/fields-auto-increment/src/Implementation.js
  packages/fields-cloudinary-image/src/Implementation.js
  packages/fields-location-google/src/Implementation.js
  packages/fields-mongoid/src/Implementation.js
  packages/fields-oembed/src/Implementation.js
  packages/fields-unsplash/src/Implementation.js
  packages/fields/src/Implementation.js
  packages/fields/src/types/CalendarDay/Implementation.js
  packages/fields/src/types/Checkbox/Implementation.js
  packages/fields/src/types/DateTime/Implementation.js
  packages/fields/src/types/DateTimeUtc/Implementation.js
  packages/fields/src/types/Decimal/Implementation.js
  packages/fields/src/types/File/Implementation.js
  packages/fields/src/types/Float/Implementation.js
  packages/fields/src/types/Integer/Implementation.js
  packages/fields/src/types/Password/Implementation.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/fields/src/types/Select/Implementation.js
  packages/fields/src/types/Text/Implementation.js
  packages/fields/src/types/Uuid/Implementation.js
  packages/fields/src/types/Virtual/Implementation.js
Labels: new interfaces, review me

#4240 Add seed data in ecommerce example
  .changeset/thick-socks-shake.md
  examples-next/ecommerce/keystone.ts
  examples-next/ecommerce/seedData.ts
Labels: new interfaces, review me

#4244 Cleaning up seed data script in the ecommerce example
  examples-next/ecommerce/keystone.ts
  examples-next/ecommerce/package.json
  examples-next/ecommerce/seed-data/data.ts
  examples-next/ecommerce/seed-data/index.ts
Labels: new interfaces

#4245 Adding portalMenu prop to Select, fixed the issue in the filter popup
  design-system/packages/fields/src/Select.tsx
  packages-next/fields/src/types/relationship/views/RelationshipSelect.tsx
  packages-next/fields/src/types/select/views/index.tsx
Labels: new interfaces

#4243 Consistency improvements in field code
  .changeset/eighty-jars-provide.md
  packages-next/cloudinary/src/index.ts
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/checkbox/index.ts
  packages-next/fields/src/types/integer/index.ts
  packages-next/fields/src/types/mongoId/index.ts
  packages-next/fields/src/types/password/index.ts
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/select/index.ts
  packages-next/fields/src/types/text/index.ts
  packages-next/fields/src/types/timestamp/index.ts
  packages-next/fields/src/types/virtual/index.ts
Labels: new interfaces, review me

#4247 Add product status field to the ecommerce example
  examples-next/ecommerce/schema.ts
Labels: new interfaces

#4241 Expanded the defaults for labelField to include "label" and "title"
  .changeset/few-actors-chew.md
  examples-next/basic/schema.ts
  examples-next/ecommerce/schema.ts
  examples-next/todo/schema.ts
  packages-next/keystone/src/lib/createKeystone.ts
Labels: new interfaces

#4263 Rename type Keystone to KeystoneSystem
  .changeset/cyan-terms-unite.md
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/home.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/templates/item.tsx
  packages-next/admin-ui/src/templates/list.tsx
  packages-next/admin-ui/src/templates/no-access.ts
  packages-next/keystone/src/lib/createAdminUIServer.ts
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/keystone/src/lib/generateAdminUI.ts
  packages-next/keystone/src/lib/itemAPI.ts
  packages-next/keystone/src/scripts/schema-type-printer.tsx
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/index.ts
  packages-next/types/src/session.ts
Labels: new interfaces, review me

#4264 Factor out _createKeystone
  .changeset/shaggy-pens-bow.md
  packages-next/keystone/src/lib/createKeystone.ts
Labels: new interfaces, review me

#4268 Add createAdminMeta to createKeystone
  .changeset/modern-socks-stare.md
  examples-next/ecommerce/CHANGELOG.md
  examples-next/todo/CHANGELOG.md
  packages-next/keystone/src/lib/createKeystone.ts
Labels: new interfaces

#4260 Updating Create Item placement and style
  .changeset/strange-snakes-walk.md
  packages-next/admin-ui/src/components/CreateItemDrawer.tsx
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterAdd.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterList.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: new interfaces

#4269 Rename KeystoneSystem objects to system
  .changeset/soft-adults-call.md
  .changeset/tough-hounds-punch.md
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/home.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/templates/item.tsx
  packages-next/admin-ui/src/templates/list.tsx
  packages-next/admin-ui/src/templates/no-access.ts
  packages-next/auth/src/index.ts
  packages-next/keystone/src/lib/createAdminUIServer.ts
  packages-next/keystone/src/lib/generateAdminUI.ts
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/scripts/schema-type-printer.tsx
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/index.ts
  packages-next/types/src/session.ts
Labels: new interfaces, review me

#4271 Factor out addApolloServer
  packages-next/keystone/src/lib/createAdminUIServer.ts
Labels: new interfaces, review me

#4274 New docs site for the new interfaces
  .github/workflows/auto-approve.yml
  docs-next/website/components/Code.tsx
  docs-next/website/components/Navigation.tsx
  docs-next/website/components/Page.tsx
  docs-next/website/next-env.d.ts
  docs-next/website/next.config.js
  docs-next/website/package.json
  docs-next/website/pages/_app.tsx
  docs-next/website/pages/guides/getting-started.tsx
  docs-next/website/pages/index.tsx
  docs-next/website/tsconfig.json
  package.json
Labels: new interfaces

#4275 New roles based access example
  examples-next/roles/README.md
  examples-next/roles/keystone.ts
  examples-next/roles/package.json
  examples-next/roles/schema.ts
Labels: new interfaces

#4246 Add addToCart and checkout mutations to ecommerce example
  .changeset/breezy-bees-live.md
  .changeset/pretty-trains-judge.md
  examples-next/ecommerce/keystone.ts
  examples-next/ecommerce/package.json
  examples-next/ecommerce/schema.ts
  packages-next/keystone/src/lib/createKeystone.ts
Labels: new interfaces, review me

#4270 Simplify auth graphQL generation
  .changeset/happy-pigs-suffer.md
  packages-next/auth/package.json
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/index.ts
Labels: new interfaces, review me

#4286 Ensure session listKey and itemId are valid in withItemData
  .changeset/cuddly-ladybugs-bathe.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces

#4287 Fixed auth when you're using a listKey other than User
  .changeset/new-lies-reflect.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
Labels: new interfaces

#4288 Fixed type for defaultFieldMode in itemView
  .changeset/shy-files-provide.md
  packages-next/types/src/schema/index.ts
Labels: new interfaces

#4289 Fixed many relationship select clipping in the Create drawer
  .changeset/nice-pants-shop.md
  packages-next/fields/src/types/relationship/views/RelationshipSelect.tsx
Labels: new interfaces

#4291 Fixed hard errors on the item screen when you can't load the item
  .changeset/four-starfishes-greet.md
  packages-next/admin-ui/src/pages/ItemPage/index.tsx
Labels: new interfaces

#4292 Implemented access control in the roles example
  examples-next/roles/access.ts
  examples-next/roles/keystone.ts
  examples-next/roles/package.json
  examples-next/roles/schema.ts
  examples-next/roles/types.ts
Labels: new interfaces

#4285 Add FIXMEs for config.graphql.path
  packages-next/admin-ui/src/components/Navigation.tsx
  packages-next/admin-ui/src/context.tsx
  packages-next/keystone/src/lib/createAdminUIServer.ts
Labels: new interfaces, review me

#4284 Simplify args to admin UI templates
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/home.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/templates/item.tsx
  packages-next/admin-ui/src/templates/list.tsx
  packages-next/admin-ui/src/templates/no-access.ts
Labels: new interfaces, review me

#4299 Rename createKeystone to createSystem
  .changeset/shy-cats-raise.md
  packages-next/keystone/src/index.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/session/index.ts
Labels: new interfaces

#4300 Remove connect and disconnect from implementSession
  .changeset/tame-eyes-lick.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces, review me

#4303 Fix sessionToken return value of auth mutation
  .changeset/cuddly-bugs-argue.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
Labels: new interfaces, review me

#4305 Use itemAPI when authenticating users
  .changeset/shy-baboons-suffer.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/lib/attemptAuthentication.ts
Labels: new interfaces, review me

#4306 Use itemAPI in authenticatedItem mutation
  .changeset/ten-pens-nail.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
Labels: new interfaces, review me

#4308 Use itemAPI in createInitialItem
  .changeset/beige-jeans-divide.md
  .changeset/little-boxes-crash.md
  .changeset/pretty-pans-bow.md
  examples-next/auth/keystone.ts
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/keystone/src/lib/itemAPI.ts
Labels: new interfaces

#4316 Improved cors support
  .changeset/quick-wombats-accept.md
  packages-next/keystone/src/lib/createAdminUIServer.ts
  packages-next/keystone/src/scripts/dev.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4302 Document field
  .changeset/strange-candles-buy.md
  .changeset/wise-mails-invent.md
  .eslintrc.js
  design-system/packages/core/src/components/Link.tsx
  examples-next/basic/.keystone/schema-types.ts
  examples-next/basic/admin/fieldViews/Content.tsx
  examples-next/basic/package.json
  examples-next/basic/schema.ts
  package.json
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/fields-document/component-blocks/package.json
  packages-next/fields-document/package.json
  packages-next/fields-document/src/DocumentEditor/Toolbar.tsx
  packages-next/fields-document/src/DocumentEditor/blockquote.tsx
  packages-next/fields-document/src/DocumentEditor/columns.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks.tsx
  packages-next/fields-document/src/DocumentEditor/components.tsx
  packages-next/fields-document/src/DocumentEditor/components/hoverable.tsx
  packages-next/fields-document/src/DocumentEditor/heading.tsx
  packages-next/fields-document/src/DocumentEditor/index.tsx
  packages-next/fields-document/src/DocumentEditor/link.tsx
  packages-next/fields-document/src/DocumentEditor/lists.tsx
  packages-next/fields-document/src/DocumentEditor/panel.tsx
  packages-next/fields-document/src/DocumentEditor/paragraphs.ts
  packages-next/fields-document/src/DocumentEditor/quote.tsx
  packages-next/fields-document/src/DocumentEditor/relationship.tsx
  packages-next/fields-document/src/DocumentEditor/render-element.tsx
  packages-next/fields-document/src/DocumentEditor/utils.ts
  packages-next/fields-document/src/Implementation.js
  packages-next/fields-document/src/base-field-type.d.ts
  packages-next/fields-document/src/base-field-type.js
  packages-next/fields-document/src/component-blocks.tsx
  packages-next/fields-document/src/index.ts
  packages-next/fields-document/src/relationship-data.tsx
  packages-next/fields-document/src/test-fixtures.js
  packages-next/fields-document/src/views.tsx
  packages-next/fields-document/views/package.json
  packages-next/fields/package.json
  packages-next/fields/types/relationship/views/RelationshipSelect/package.json
  packages-next/types/src/admin-meta.ts
  tests/api-tests/fields/crud.test.js
  tests/api-tests/fields/filter.test.js
  tests/api-tests/fields/required.test.js
  tests/api-tests/fields/unique.test.js
  tests/api-tests/fields/unsupported.test.js
  yarn.lock
Labels: new interfaces

#4318 Use itemAPI in updateAuthToken
  .changeset/forty-weeks-wink.md
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/updateAuthToken.ts
Labels: new interfaces, review me

#4317 Add createGraphQLSchema to createSystem
  .changeset/chilly-waves-hide.md
  packages-next/keystone/src/lib/createSystem.ts
Labels: new interfaces, review me

#4338 Update renovate config to be less busy
  renovate.json
Labels: review me

#4341 Use explicitly silenced errors rather than warnings for disabled tests
  .eslintrc.js
  packages/adapter-prisma/tests/adapter-prisma.test.js
  tests/api-tests/relationships/filtering/nested.test.js
Labels: review me

#4348 Adding Document field spec and TODO file
  packages-next/fields-document/TODO.md
Labels: new interfaces

#4359 Minor tweaks to renovate config
  renovate.json
Labels: review me

#4362 More renovate tweaks
  renovate.json
Labels: review me

#4365 Configure renovate for slate packages
  renovate.json
Labels: review me

#4370 Code cleanup through magic-auth-link code paths
  .changeset/eighty-readers-bow.md
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/redeemAuthToken.ts
  packages-next/auth/src/lib/validateAuthToken.ts
  packages-next/fields-document/TODO.md
Labels: new interfaces, review me

#4371 Document and tweak generateToken
  .changeset/angry-ears-walk.md
  packages-next/auth/src/lib/generateToken.ts
Labels: new interfaces, review me

#4372 Fix return value of sendItemPasswordResetLink
  .changeset/wild-rivers-arrive.md
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/updateItemSecret.ts
Labels: new interfaces, review me

#4373 Dividers in document field
  examples-next/basic/schema.ts
  packages-next/fields-document/src/DocumentEditor/Toolbar.tsx
  packages-next/fields-document/src/DocumentEditor/divider.tsx
  packages-next/fields-document/src/DocumentEditor/index.tsx
  packages-next/fields-document/src/DocumentEditor/render-element.tsx
  packages-next/fields-document/src/DocumentEditor/utils.ts
  packages-next/fields-document/src/index.ts
  packages-next/fields-document/src/views.tsx
Labels: new interfaces

#4374 Pass through itemAPI rather than full context in auth lib
  .changeset/green-hornets-hammer.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/attemptAuthentication.ts
  packages-next/auth/src/lib/redeemAuthToken.ts
  packages-next/auth/src/lib/updateAuthToken.ts
  packages-next/auth/src/lib/validateAuthToken.ts
Labels: new interfaces, review me

#4378 Use context consistently
  .changeset/three-numbers-impress.md
  examples-next/basic/schema.ts
  examples-next/ecommerce/schema.ts
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/fields-document/src/Implementation.js
  packages-next/fields/src/types/virtual/index.ts
  packages-next/keystone/src/lib/createSystem.ts
Labels: new interfaces, review me

#4379 Refactor auth token handling
  .changeset/witty-vans-rescue.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/generateToken.ts
  packages-next/auth/src/lib/redeemAuthToken.ts
  packages-next/auth/src/lib/updateAuthToken.ts
Labels: new interfaces, review me

#4380 Rename attemptAuthentication to validateSecret
  .changeset/moody-wolves-obey.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/lib/validateSecret.ts
Labels: new interfaces, review me

#4381 Use validateSecret in validateAuthItem
  .changeset/thirty-poems-eat.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/lib/validateAuthToken.ts
  packages-next/auth/src/lib/validateSecret.ts
Labels: new interfaces, review me

#4383 Factor out findMatchingIdentity
  .changeset/stupid-vans-care.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/findMatchingIdentity.ts
  packages-next/auth/src/lib/updateAuthToken.ts
  packages-next/auth/src/lib/validateAuthToken.ts
  packages-next/auth/src/lib/validateSecret.ts
  packages-next/auth/src/types.ts
Labels: new interfaces, review me

#4404 Add spacing between the signin header and form
  .changeset/loud-bugs-wait.md
  packages-next/auth/src/pages/SigninPage.tsx
Labels: new interfaces

#4406 Factor out createContext from createSystem
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/createSystem.ts
Labels: new interfaces

#4410 Refactor other methods out of createSystem
  packages-next/keystone/src/lib/applyIdFieldDefaults.ts
  packages-next/keystone/src/lib/createAdminMeta.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/keystone/src/lib/createSystem.ts
Labels: new interfaces

#4407 Show list label instead of "item" when linking to related items
  .changeset/wise-wolves-camp.md
  packages-next/fields/src/types/relationship/views/cards/index.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: new interfaces

#4414 Type keystone context
  .changeset/rotten-cows-speak.md
  examples-next/basic/schema.ts
  examples-next/ecommerce/mutations.ts
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/fields/src/types/virtual/index.ts
  packages-next/keystone/src/lib/createAccessControlContext.ts
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/schema/schema.ts
  packages-next/types/src/index.ts
  packages-next/types/src/schema/access-control.ts
  packages-next/types/src/schema/hooks.ts
  packages-next/types/src/utils.ts
Labels: new interfaces

#4426 Use KeystoneContext type where appropriate
  .changeset/tidy-bugs-crash.md
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/fields-document/CHANGELOG.md
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/types/src/index.ts
Labels: review me

#4427 Core keystone type
  .changeset/nasty-dingos-punch.md
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/keystone/src/lib/createAdminMeta.ts
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/index.ts
Labels: review me

#4433 Updated InitPage to fix the error with the new field value shape
  .changeset/nasty-dingos-punch.md
  .changeset/tame-ducks-promise.md
  packages-next/auth/src/pages/InitPage.tsx
Labels: new interfaces

#4432 Remove need to pass adminMeta to makeCreateContext
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/createSystem.ts
Labels: review me

#4431 Reorder lint run order for faster failure
  .github/workflows/tests.yml
Labels: review me

#4440 Fixed onConnect arguments and added database APIs to context
  .changeset/wet-eyes-clean.md
  examples-next/ecommerce/keystone.ts
  examples-next/ecommerce/seed-data/index.ts
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me
