Repository keystonejs/keystone, pull requests merged in 2020-07, with the labels that each got.

#3169 Remove query argument to custom resolvers
  .changeset/orange-actors-listen.md
  docs/guides/custom-schema.md
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/providers/custom.js
Labels: needs-clarification

#3172 Remove keystone.executeQuery
  .changeset/silent-berries-swim.md
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#3175 Remove authedItem and authedListKey from SessionManager.getContext
  .changeset/lazy-numbers-leave.md
  packages/session/lib/session.js
Labels: needs-clarification

#3171 Remove actions argument to hooks
  .changeset/nice-bags-type.md
  api-tests/default-value/defaults.test.js
  demo-projects/custom-fields/fields/MultiCheck/Implementation.js
  docs/api/hooks.md
  packages/fields/README.md
  packages/fields/src/Implementation.js
  packages/fields/tests/Implementation.test.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/tests/List.test.js
Labels: needs-clarification

#3173 Remove _buildQueryHelper and _executeOperation
  .changeset/famous-stingrays-add.md
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#3174 Replace getGraphQlContext with createHTTPContext
  .changeset/spotty-poets-beg.md
  packages/app-graphql/lib/apolloServer.js
  packages/keystone/lib/Keystone/index.js
Labels: needs-clarification

#3225 Fix bug where fields that contain underscores cause runtime error in Knex Adapter
  .changeset/dirty-points-work.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#3234 Factor out list utils
  .changeset/lucky-jokes-warn.md
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/lib/ListTypes/utils.js
Labels: needs-clarification

#3233 Update access control functions
  .changeset/pretty-radios-obey.md
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/lib/providers/listAuth.js
  packages/keystone/tests/List.test.js
Labels: needs-clarification

#2745 Allowed configuring default/maximumPageSize for all lists
  .changeset/tasty-cooks-begin.md
  packages/app-admin-ui/README.md
  packages/app-admin-ui/index.js
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/lib/ListTypes/utils.js
  packages/keystone/tests/List.test.js
Labels: admin-ui, merge conflict

#2500 [RFC] New API doc formatting proposal
  packages/keystone/README.md
Labels: merge conflict

#3246 Update calendarDay example in docs
  docs/tutorials/add-lists.md
Labels: needs-clarification

#3245 Allow passing in `null` value to CalendarDay field
  .changeset/lucky-buckets-carry.md
  packages/fields/src/types/CalendarDay/Implementation.js
Labels: needs-clarification

#3250 Split search test into separate tests
  .changeset/strong-colts-sing.md
  api-tests/queries/search.test.js
Labels: needs-clarification

#3251 Check for errors in matchFilter
  .changeset/silent-onions-taste.md
  packages/fields/tests/test-fixtures.js
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#3252 Allow DATABASE_URL in api-tests
  .changeset/cold-lies-kiss.md
  .circleci/config.yml
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#3264 Fix _is_null query on 1:1 relationships
  .changeset/twenty-baboons-rest.md
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
  packages/adapter-knex/lib/adapter-knex.js
Labels: review me

#3265 Call jest.setTimeout from jest/setup.js
  .changeset/red-pandas-punch.md
  api-tests/access-control/authed.test.js
  api-tests/access-control/not-authed.test.js
  api-tests/access-control/schema.test.js
  api-tests/fields.test.js
  api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/many-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/many-to-many-one-sided.test.js
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-one-required.test.js
  jest/setup.js
  packages/build-field-types/src/__tests__/dev.js
  packages/mongo-join-builder/tests/mongo-results.test.js
Labels: review me

#3266 Make test code more consistent
  .changeset/fresh-gifts-type.md
  api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/many-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/many-to-many-one-sided.test.js
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
Labels: review me

#3267 Use a consistent pattern for setting up keystone in relationship tests
  .changeset/big-snakes-trade.md
  api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/many-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/many-to-many-one-sided.test.js
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
Labels: needs-clarification

#3274 Add cache hints to extended graphql queries
  .changeset/many-laws-compare.md
  api-tests/queries/cache-hints.test.js
  docs/api/create-list.md
  docs/guides/cache-hints.md
  docs/guides/production.md
  packages/keystone/lib/providers/custom.js
Labels: core, graphql

#3277 Upgrade Jest to v26
  .changeset/breezy-planets-dream.md
  package.json
  packages/build-field-types/package.json
  yarn.lock
Labels: review me

#3278 Replace pFinally with native code
  .changeset/wet-buttons-collect.md
  packages/test-utils/lib/test-utils.js
  packages/test-utils/package.json
  yarn.lock
Labels: needs-clarification

#3281 Remove dependency on return order of many-relationships in api-tests
  .changeset/popular-maps-juggle.md
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/filtering/filtering.test.js
  api-tests/relationships/filtering/nested.test.js
Labels: needs-clarification, review me

#3282 Pass rels to adapter._connect()
  .changeset/neat-geckos-rush.md
  packages/keystone/lib/adapters/index.js
Labels: needs-clarification

#3283 Move mongoose specific code into mongo-join-builder
  .changeset/bright-badgers-relate.md
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/keystone/lib/adapters/index.js
  packages/mongo-join-builder/lib/tokenizers.js
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/relationship-path.test.js
  packages/mongo-join-builder/tests/relationship.test.js
  packages/mongo-join-builder/tests/utils.js
Labels: review me

#3286 Fix a small typo in custom fields tutorial (docs)
  docs/tutorials/custom-fields.md
Labels: needs-clarification

#3284 Move more mongoose specific code into mongo-join-builder
  .changeset/long-days-retire.md
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/mongo-join-builder/lib/tokenizers.js
  packages/mongo-join-builder/tests/relationship-path.test.js
  packages/mongo-join-builder/tests/relationship.test.js
  packages/mongo-join-builder/tests/utils.js
Labels: review me

#3289 Remove keystone.createHTTPContext
  .changeset/fast-donkeys-cheat.md
  packages/keystone/lib/Keystone/index.js
Labels: review me

#3290 Use a consistent if (this.many) {} else {} pattern in relationships
  .changeset/wicked-bikes-fry.md
  packages/fields/src/types/Relationship/Implementation.js
Labels: review me

#3297 Clean up master
  packages/app-admin-ui/CHANGELOG.md
  packages/app-admin-ui/README.md
  yarn.lock
Labels: review me

#3299 Fix isUnique for DateTime on MongooseAdapter
  .changeset/dry-balloons-tell.md
  .changeset/sixty-brooms-work.md
  api-tests/required.test.js
  api-tests/uniqueness/unique.test.js
  packages/field-content/src/test-fixtures.skip.js
  packages/fields-authed-relationship/src/test-fixtures.skip.js
  packages/fields-auto-increment/src/Implementation.js
  packages/fields-auto-increment/src/test-fixtures.skip.js
  packages/fields-datetime-utc/src/Implementation.js
  packages/fields-datetime-utc/src/test-fixtures.js
  packages/fields-markdown/src/test-fixtures.js
  packages/fields-mongoid/src/Implementation.js
  packages/fields-mongoid/src/test-fixtures.js
  packages/fields-wysiwyg-tinymce/src/test-fixtures.js
  packages/fields/src/Implementation.js
  packages/fields/src/types/CalendarDay/Implementation.js
  packages/fields/src/types/CalendarDay/test-fixtures.js
  packages/fields/src/types/Checkbox/Implementation.js
  packages/fields/src/types/Checkbox/test-fixtures.js
  packages/fields/src/types/CloudinaryImage/test-fixtures.js
  packages/fields/src/types/Color/test-fixtures.js
  packages/fields/src/types/DateTime/Implementation.js
  packages/fields/src/types/DateTime/test-fixtures.js
  packages/fields/src/types/Decimal/Implementation.js
  packages/fields/src/types/Decimal/test-fixtures.js
  packages/fields/src/types/File/Implementation.js
  packages/fields/src/types/File/test-fixtures.js
  packages/fields/src/types/Float/Implementation.js
  packages/fields/src/types/Float/test-fixtures.js
  packages/fields/src/types/Integer/Implementation.js
  packages/fields/src/types/Integer/test-fixtures.js
  packages/fields/src/types/Location/Implementation.js
  packages/fields/src/types/Location/test-fixtures.js
  packages/fields/src/types/OEmbed/Implementation.js
  packages/fields/src/types/OEmbed/test-fixtures.js
  packages/fields/src/types/Password/Implementation.js
  packages/fields/src/types/Password/test-fixtures.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/fields/src/types/Select/Implementation.js
  packages/fields/src/types/Select/test-fixtures.js
  packages/fields/src/types/Slug/test-fixtures.skip.js
  packages/fields/src/types/Text/Implementation.js
  packages/fields/src/types/Text/test-fixtures.js
  packages/fields/src/types/Unsplash/Implementation.js
  packages/fields/src/types/Unsplash/test-fixtures.js
  packages/fields/src/types/Url/test-fixtures.js
  packages/fields/src/types/Uuid/Implementation.js
  packages/fields/src/types/Uuid/test-fixtures.js
  packages/fields/src/types/Virtual/Implementation.js
Labels: review me

#3309 Rename default schema from 'testing' to 'public'
  .changeset/chatty-dancers-hunt.md
  .changeset/young-months-drop.md
  api-tests/auth-header.test.js
  api-tests/extend-graphql-schema/extend-graphql-schema.test.js
  api-tests/fields.test.js
  packages/server-side-graphql-client/tests/index.test.js
  packages/test-utils/lib/test-utils.js
Labels: review me

#3302 Remove createitems
  .changeset/hot-olives-reply.md
  docs/tutorials/initial-data.md
  packages/keystone/README.md
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/Keystone/relationship-utils.js
  packages/keystone/tests/Keystone.test.js
  packages/keystone/tests/relationship-utils.test.js
Labels: review me

#3312 Use keystone.executeGraphQL in place of authedGraphqlRequest
  .changeset/silver-numbers-flash.md
  api-tests/access-control/authed.test.js
  api-tests/access-control/not-authed.test.js
  api-tests/extend-graphql-schema/extend-graphql-schema.test.js
  api-tests/relationships/filtering/access-control.test.js
  api-tests/relationships/nested-mutations/connect-many.test.js
  api-tests/relationships/nested-mutations/connect-singular.test.js
  api-tests/relationships/nested-mutations/create-and-connect-many.test.js
  api-tests/relationships/nested-mutations/create-many.test.js
  api-tests/relationships/nested-mutations/create-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-all-many.test.js
  api-tests/relationships/nested-mutations/disconnect-all-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-many.test.js
  api-tests/relationships/nested-mutations/disconnect-singular.test.js
Labels: needs-clarification, review me

#3311 Use server side graphql client functions in tests
  .changeset/warm-phones-play.md
  api-tests/relationships/nested-mutations/connect-singular.test.js
  api-tests/relationships/nested-mutations/create-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-all-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-singular.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-one-required.test.js
Labels: needs-clarification, review me
