Repository keystonejs/keystone, pull requests merged in 2020-04, with the labels that each got.

#2627 Document missing argument in custom resolver functions
  .changeset/lazy-elephants-repeat.md
  packages/keystone/README.md
Labels: docs

#2634 Update changesets to improve grammar and messaging
  .changeset/eight-bugs-remember.md
  .changeset/forty-jokes-swim.md
  .changeset/khaki-otters-sort.md
  .changeset/large-icons-wash.md
  .changeset/metal-avocados-juggle.md
  .changeset/nervous-horses-juggle.md
  .changeset/slow-bikes-wonder.md
  .changeset/thick-cobras-hammer.md
Labels: needs-clarification

#2649 Tweak wording and link to sessionStore heading
  docs/guides/production.md
Labels: needs-clarification

#2000 Update the implementation of relationship in adapters
  .changeset/silent-eyes-yell.md
  api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/many-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/many-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
  api-tests/relationships/nested-mutations/reconnect-many-to-one.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-one-required.test.js
  demo-projects/relationships/index.js
  demo-projects/relationships/package.json
  docs/discussions/database-schema.md
  docs/discussions/index.md
  docs/discussions/new-data-schema.md
  docs/discussions/relationships.md
  docs/guides/apps.md
  docs/guides/graphql-philosophy.md
  docs/guides/mutation-lifecycle.md
  docs/guides/new-schema-cheatsheet.md
  docs/guides/relationship-migration.md
  docs/guides/relationships.md
  docs/quick-start/README.md
  docs/tutorials/relationships.md
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/adapter-mongoose/tests/list-adapter.test.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/fields/src/types/Relationship/backlinks.js
  packages/fields/src/types/Relationship/index.js
  packages/keystone/bin/commands/upgrade-relationships.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/List/index.js
  packages/mongo-join-builder/README.md
  packages/mongo-join-builder/lib/join-builder.js
  packages/mongo-join-builder/lib/query-parser.js
  packages/mongo-join-builder/lib/tokenizers.js
  packages/mongo-join-builder/tests/index.test.js
  packages/mongo-join-builder/tests/join-builder.test.js
  packages/mongo-join-builder/tests/mongo-results.test.js
  packages/mongo-join-builder/tests/query-parser.test.js
  packages/mongo-join-builder/tests/relationship.test.js
  packages/mongo-join-builder/tests/utils.js
Labels: needs-clarification

#2666 Fix count queries on one-to-one relationships
  .changeset/curvy-ants-wave.md
  .changeset/large-cheetahs-begin.md
  api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/many-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/many-to-many-one-sided.test.js
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
Labels: needs-clarification

#2695 Update local yarn.lock to clear out some yarn audit warnings
  yarn.lock
Labels: needs-clarification

#2717 Fix missed import
  docs/tutorials/add-lists.md
Labels: needs-clarification

#2718 Fix typo in "Database Setup"
  docs/quick-start/README.md
Labels: needs-clarification

#2722 Typo fix
  docs/guides/mutation-lifecycle.md
Labels: needs-clarification

#2674 Update cypress to 4.3.0
  .changeset/quick-deers-chew.md
  package.json
  test-projects/access-control/cypress/integration/field/graphql.js
  test-projects/access-control/cypress/integration/list/graphql.js
  test-projects/access-control/package.json
  test-projects/basic/package.json
  test-projects/client-validation/package.json
  test-projects/login/package.json
  yarn.lock
Labels: needs-clarification

#2720 Typo fix
  docs/guides/hooks.md
Labels: needs-clarification

#2724 Used functional components for email templates
  .changeset/yellow-windows-tan.md
  demo-projects/meetup/emails/forgot-password.jsx
  demo-projects/meetup/emails/password-updated.jsx
  packages/email/tests/jsx-views/view.jsx
  packages/email/tests/mjml-views/view.jsx
Labels: needs-clarification

#2785 Fix where queries on 1:1 relationships for knex
  .changeset/empty-oranges-hunt.md
  .changeset/tasty-kangaroos-raise.md
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/one-to-one.test.js
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification

#2784 Move access control tests to api-tests
  .changeset/sharp-peaches-train.md
  api-tests/access-control/authed.test.js
  test-projects/access-control/cypress/integration/list/graphql.js
Labels: needs-clarification

#2796 Fix updating one-to-one values
  .changeset/pink-kids-try.md
  api-tests/relationships/crud/one-to-one.test.js
  packages/adapter-knex/lib/adapter-knex.js
  packages/adapter-mongoose/lib/adapter-mongoose.js
Labels: needs-clarification

#2807 Fix bug querying one-to-one relationships with mongoose
  .changeset/dirty-points-smoke.md
  api-tests/relationships/crud/one-to-one.test.js
  packages/mongo-join-builder/lib/join-builder.js
Labels: needs-clarification

#2813 Fix bug in AuthedRelationship field when no access control set
  .changeset/green-boats-walk.md
  packages/fields-authed-relationship/src/Implementation.js
Labels: auth, needs-clarification

#2811 Use AuthedRelationship to power byTracking
  .changeset/polite-baboons-fetch.md
  packages/list-plugins/lib/tracking/byTracking.js
  packages/list-plugins/package.json
Labels: auth, plugin

#2814 Pass context to authStrategy.validate
  .changeset/breezy-stingrays-juggle.md
  packages/keystone/lib/providers/listAuth.js
Labels: needs-clarification

#2845 Bump patch level dependencies
  .changeset/spotty-pugs-build.md
  api-tests/package.json
  benchmarks/package.json
  package.json
  packages/app-admin-ui/package.json
  packages/build-field-types/package.json
  packages/fields-wysiwyg-tinymce/package.json
  packages/test-utils/package.json
  yarn.lock
Labels: needs-clarification

#2854 Upgrade dependencies of app-graphql
  .changeset/selfish-poets-bake.md
  api-tests/package.json
  benchmarks/package.json
  package.json
  packages/app-graphql/lib/apolloServer.js
  packages/app-graphql/package.json
  packages/fields-wysiwyg-tinymce/package.json
  packages/fields/package.json
  packages/mongo-join-builder/package.json
  yarn.lock
Labels: needs-clarification
