Repository keystonejs/keystone, pull requests merged in 2020-12, with the labels that each got.

#4424 Types for listQuery and similar
  .changeset/soft-impalas-remember.md
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/types/src/index.ts
  packages-next/types/src/utils.ts
Labels: review me

#4452 Use the current context with the item API
  .changeset/thick-beers-train.md
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/itemAPI.ts
Labels: new interfaces, review me

#4455 Rename createAdminUIServer to createExpressServer
  .changeset/little-pumpkins-repeat.md
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces, review me

#4453 Maintain session info on new contexts
  .changeset/blue-spies-mix.md
  packages-next/keystone/src/lib/createContext.ts
Labels: new interfaces, review me

#4460 Rename sessionStrategy to asSessionStrategy
  .changeset/eight-numbers-remember.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces, review me

#4461 Use type parameter in implementSession
  .changeset/silent-brooms-punch.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces, review me

#4458 Put sessionImplementation on the system object
  .changeset/pink-years-return.md
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4456 Use original config object, not system.config
  .changeset/chilled-onions-type.md
  packages-next/admin-ui/src/templates/index.ts
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/lib/generateAdminUI.ts
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces, review me

#4451 Factor out getArgs in items API
  .changeset/lucky-eels-sin.md
  packages-next/keystone/src/lib/itemAPI.ts
Labels: new interfaces, review me

#4465 [RFC] Make SessionStrategy.start and SessionStrategy.end required
  .changeset/eight-taxis-lick.md
  packages-next/types/src/session.ts
Labels: new interfaces, review me

#4468 Precompute arg-parsing functions
  .changeset/silent-donkeys-work.md
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/itemAPI.ts
Labels: new interfaces, review me

#4466 Add return type for statelessSessions
  .changeset/stale-carrots-wink.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces, review me

#4469 Replace any with explicit type
  packages-next/keystone/src/lib/itemAPI.ts
Labels: new interfaces, review me

#4470 Refactor createGraphQLSchema for improved readability
  packages-next/keystone/src/lib/createGraphQLSchema.ts
Labels: new interfaces, review me

#4472 Remove auto-approval workflow
  .github/workflows/auto-approve.yml
Labels: review me

#4473 Add a resolveFields argument to the item API methods
  .changeset/brown-melons-jump.md
  .changeset/good-falcons-protect.md
  examples-next/ecommerce/mutations.ts
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/itemAPI.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4454 Decouple keystone.connect() from admin UI setup
  .changeset/famous-walls-laugh.md
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces, review me

#4464 Factor out createAdminUIServer
  packages-next/keystone/src/lib/createExpressServer.ts
Labels: new interfaces

#4467 Add type for BaseKeystone.createApolloServer
  .changeset/old-ghosts-provide.md
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4474 Remove unneeded calls to JSON.stringify
  .changeset/brave-flies-crash.md
  packages-next/auth/src/index.ts
  packages-next/auth/src/templates/init.ts
  packages-next/auth/src/templates/signin.ts
Labels: new interfaces, review me

#4475 Use SerializedAdminMeta type for adminMeta
  .changeset/happy-lemons-search.md
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4476 Replace any with more specific types
  .changeset/tough-queens-judge.md
  packages-next/auth/src/lib/findMatchingIdentity.ts
  packages-next/auth/src/lib/updateAuthToken.ts
  packages-next/auth/src/lib/validateAuthToken.ts
  packages-next/auth/src/lib/validateSecret.ts
  packages-next/keystone/src/lib/createExpressServer.ts
Labels: new interfaces, review me

#4477 Make SessionContext properties required
  .changeset/empty-adults-obey.md
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4478 Factor out base keystone types
  .changeset/lucky-masks-enjoy.md
  packages-next/types/src/base.ts
  packages-next/types/src/core.ts
  packages-next/types/src/index.ts
Labels: new interfaces, review me

#4459 Apply applyIdFieldDefaults before createSystem
  .changeset/plenty-donkeys-live.md
  packages-next/keystone/src/lib/applyIdFieldDefaults.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/keystone/src/lib/initConfig.ts
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces, review me

#4485 Updating auth extensions to skip access control after the context API changes
  .changeset/few-pillows-lie.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
  packages-next/auth/src/gql/getInitFirstItemSchema.ts
  packages-next/auth/src/gql/getMagicAuthLinkSchema.ts
  packages-next/auth/src/gql/getPasswordResetSchema.ts
  packages-next/auth/src/lib/findMatchingIdentity.ts
Labels: new interfaces, review me

#4471 Simplify code with SessionStrategy.end and .start being required
  .changeset/eighty-doors-jump.md
  packages-next/keystone/src/lib/createAdminMeta.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/keystone/src/session/index.ts
Labels: new interfaces, review me

#4484 Move admin UI code into admin UI package
  .changeset/tidy-hounds-smell.md
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/admin-ui/src/system/generateAdminUI.ts
  packages-next/admin-ui/src/system/index.ts
  packages-next/admin-ui/system/package.json
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces, review me

#4488 Use items API in ecommerce project
  .changeset/yellow-apes-cover.md
  examples-next/ecommerce/mutations.ts
  examples-next/ecommerce/package.json
Labels: new interfaces, review me

#4487 Calculate isAccessAllowed inside adminMetaSchemaExtension
  .changeset/shiny-taxis-approve.md
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
Labels: new interfaces, review me

#4489 Improve type readability
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
Labels: new interfaces, review me

#4492 Pass createContext rather than system to session functions
  .changeset/smooth-snails-mate.md
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/core.ts
  packages-next/types/src/session.ts
Labels: new interfaces, review me

#4497 Use KeystoneContext type in admin meta resolvers
  .changeset/sweet-suns-hope.md
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
Labels: new interfaces, review me

#4483 Disabled the debug output by default in the Document field
  packages-next/fields-document/src/DocumentEditor/index.tsx
Labels: new interfaces, review me

#4498 Fix up keystone as any
  .changeset/real-melons-add.md
  packages-next/keystone/src/lib/createAdminMeta.ts
  packages-next/keystone/src/lib/createContext.ts
  packages-next/types/src/base.ts
Labels: new interfaces, review me

#4500 Remove dependency on adminMeta when generating schema types
  .changeset/mean-lemons-rule.md
  packages-next/keystone/src/scripts/schema-type-printer.tsx
Labels: new interfaces, review me

#4494 Rename KeystoneSystem.views to KeystoneSystem.allViews
  .changeset/chatty-tips-taste.md
  packages-next/admin-ui/src/templates/app.ts
  packages-next/keystone/src/lib/createAdminMeta.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4493 Rename SerializedFieldMeta.views to SerializedFieldMeta.viewsIndex
  .changeset/angry-shoes-watch.md
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/keystone/src/lib/createAdminMeta.ts
  packages-next/types/src/admin-meta.ts
Labels: new interfaces, review me

#4482 Remove config from system
  .changeset/four-ducks-taste.md
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/admin-ui/src/system/generateAdminUI.ts
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/auth/src/index.ts
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4499 Remove schema merge from adminMetaSchemaExtension
  .changeset/clean-pants-judge.md
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
Labels: new interfaces, review me

#4490 Improve correctness of adminMetaSchemaExtension
  .changeset/dry-grapes-turn.md
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
Labels: new interfaces

#4496 Simplify getLazyMetadataQuery
  .changeset/eleven-singers-watch.md
  packages-next/admin-ui/src/templates/app.ts
Labels: new interfaces, review me

#4501 Remove sessionImplementation from KeystoneSystem
  .changeset/chatty-roses-joke.md
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4502 Fixed key missed in #4493, rename views to viewsIndex
  packages-next/admin-ui/src/admin-meta-graphql.ts
Labels: new interfaces, review me

#4503 Added resolveFields: false to the authenticatedItem query
  packages-next/auth/src/gql/getBaseAuthSchema.ts
Labels: new interfaces, review me

#4495 Simplify generateAdminUI
  .changeset/fuzzy-pants-learn.md
  packages-next/admin-ui/src/system/generateAdminUI.ts
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces, review me

#4524 Fixed an issue where invalid items would crash session initialisation
  .changeset/odd-shoes-chew.md
  packages-next/keystone/src/session/index.ts
Labels: new interfaces, review me

#4491 Simplify admin UI generation
  .changeset/lemon-kids-tease.md
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/home.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/templates/item.tsx
  packages-next/admin-ui/src/templates/list.tsx
  packages-next/admin-ui/src/templates/no-access.ts
Labels: new interfaces, review me

#4509 Replace KeystoneAdminUIConfig.system with createContext
  .changeset/seven-beds-trade.md
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/auth/src/index.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4522 Factour out argGenerator
  .changeset/nine-gorillas-smell.md
  packages/test-utils/lib/test-utils.js
Labels: new interfaces, review me

#4523 Full database config support
  .changeset/loud-cobras-peel.md
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/applyIdFieldDefaults.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4526 Fix error in authenticatedItem resolver
  .changeset/gold-chairs-flow.md
  packages-next/auth/src/gql/getBaseAuthSchema.ts
Labels: new interfaces, review me

#4527 Add req to KeystoneContext
  .changeset/wild-ears-knock.md
  packages-next/keystone/src/lib/createContext.ts
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4529 Add missing attributes to FieldMeta
  .changeset/plenty-dots-impress.md
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/types/src/admin-meta.ts
Labels: new interfaces, review me

#4528 Pass context to KeystoneAdminUIConfig.isAccessAllowed
  .changeset/yellow-mice-join.md
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4530 Pass explicit args to printGeneratedTypes
  .changeset/heavy-worms-clean.md
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/scripts/schema-type-printer.tsx
Labels: new interfaces, review me

#4531 Pass explicit args to addApolloServer
  .changeset/proud-ads-juggle.md
  packages-next/keystone/src/lib/createExpressServer.ts
Labels: new interfaces, review me

#4534 Generate lazyMetadataQuery from staticAdminMetaQuery
  .changeset/shaggy-badgers-cheat.md
  packages-next/admin-ui/src/templates/app.ts
Labels: new interfaces, review me

#4532 Move templates/adminMetaSchemaExtension to system/getAdminMetaSchema
  .changeset/gorgeous-impalas-look.md
  packages-next/admin-ui/src/system/getAdminMetaSchema.ts
  packages-next/admin-ui/src/system/index.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
Labels: new interfaces, review me

#4533 Rename SessionImplementation.createContext to createSessionContext
  .changeset/small-plants-repair.md
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me

#4535 Export initConfig
  .changeset/hot-bananas-protect.md
  packages-next/keystone/src/index.ts
Labels: new interfaces

#4536 Improve mongo query efficiency
  .changeset/olive-pillows-fetch.md
  packages/adapter-mongoose/lib/query-parser.js
Labels: review me

#4510 Add support for new interfaces to @keystonejs/test-utils
  .changeset/clean-phones-double.md
  packages/test-utils/index.js
  packages/test-utils/lib/test-utils.js
  packages/test-utils/package.json
  tests/api-tests/new-interfaces.test.js
  tests/api-tests/package.json
Labels: new interfaces, review me

#4544 Replace useCompiledBcrypt option with bcrypt option
  .changeset/dirty-spies-cry.md
  packages-next/fields/package.json
  packages-next/fields/src/types/password/index.ts
  packages/fields/src/types/Password/Implementation.js
  packages/fields/src/types/Password/README.md
  yarn.lock
Labels: review me

#4525 Use adminMeta query in init item page
  .changeset/modern-taxis-doubt.md
  packages-next/auth/src/index.ts
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/auth/src/templates/init.ts
Labels: new interfaces, review me

#4546 Fix bug in auth isAccessAllowed
  packages-next/auth/src/index.ts
Labels: new interfaces

#4545 Move createAdminMeta into admin-ui package
  .changeset/strong-mails-applaud.md
  packages-next/admin-ui/src/system/createAdminMeta.ts
  packages-next/admin-ui/src/system/index.ts
  packages-next/keystone/src/lib/createSystem.ts
Labels: new interfaces, review me

#4548 build and start commands for new interfaces
  .changeset/many-lies-visit.md
  .changeset/wise-chairs-mate.md
  packages-next/admin-ui/src/system/buildAdminUI.ts
  packages-next/admin-ui/src/system/createAdminUIServer.ts
  packages-next/admin-ui/src/system/generateAdminUI.ts
  packages-next/admin-ui/src/system/index.ts
  packages-next/keystone/bin/cli.js
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/scripts/build.ts
  packages-next/keystone/src/scripts/cli.ts
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/scripts/index.ts
  packages-next/keystone/src/scripts/start.ts
  packages-next/keystone/src/scripts/utils.ts
  yarn.lock
Labels: new interfaces, review me

#4550 Force the Admin UI to use consistent versions of react, react-dom and @keystone-next/admin-ui
  .changeset/giant-zebras-collect.md
  packages-next/admin-ui/next-config/package.json
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/next-config.ts
  packages-next/admin-ui/static/next.config.js
Labels: new interfaces

#4547 Remove allViews from KeystoneSystem
  .changeset/unlucky-shoes-fetch.md
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/system/createAdminMeta.ts
  packages-next/admin-ui/src/system/generateAdminUI.ts
  packages-next/admin-ui/src/system/getAdminMetaSchema.ts
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/admin-ui/src/utils/viewHash.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/core.ts
Labels: new interfaces

#4549 Add start and build scripts to examples-next
  examples-next/auth/package.json
  examples-next/basic/package.json
  examples-next/ecommerce/package.json
  examples-next/roles/package.json
  examples-next/todo/package.json
Labels: new interfaces

#4572 Fix example code in Virtual field docs
  packages/fields/src/types/Virtual/README.md
Labels: docs, review me

#4573 Copy rather than mutate in initConfig
  .changeset/long-rocks-study.md
  packages-next/keystone/src/lib/initConfig.ts
Labels: new interfaces, review me

#4556 Document field normalization, fixes and tests
  examples-next/basic/admin/fieldViews/Content.tsx
  packages-next/fields-document/TODO.md
  packages-next/fields-document/package.json
  packages-next/fields-document/src/DocumentEditor/Toolbar.tsx
  packages-next/fields-document/src/DocumentEditor/blockquote.test.tsx
  packages-next/fields-document/src/DocumentEditor/blockquote.tsx
  packages-next/fields-document/src/DocumentEditor/code-block.test.tsx
  packages-next/fields-document/src/DocumentEditor/code-block.tsx
  packages-next/fields-document/src/DocumentEditor/columns.test.tsx
  packages-next/fields-document/src/DocumentEditor/columns.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/api.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/form.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/index.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/initial-values.ts
  packages-next/fields-document/src/DocumentEditor/component-blocks/insert-break-and-delete.test.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/insertion-and-preview-props.test.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/normalization.test.tsx
  packages-next/fields-document/src/DocumentEditor/component-blocks/preview-props.ts
  packages-next/fields-document/src/DocumentEditor/component-blocks/utils.ts
  packages-next/fields-document/src/DocumentEditor/component-blocks/with-component-blocks.tsx
  packages-next/fields-document/src/DocumentEditor/divider.test.tsx
  packages-next/fields-document/src/DocumentEditor/heading.test.tsx
  packages-next/fields-document/src/DocumentEditor/heading.tsx
  packages-next/fields-document/src/DocumentEditor/index.tsx
  packages-next/fields-document/src/DocumentEditor/link.tsx
  packages-next/fields-document/src/DocumentEditor/lists.test.tsx
  packages-next/fields-document/src/DocumentEditor/lists.tsx
  packages-next/fields-document/src/DocumentEditor/paragraphs.ts
  packages-next/fields-document/src/DocumentEditor/relationship.tsx
  packages-next/fields-document/src/DocumentEditor/render-element.tsx
  packages-next/fields-document/src/DocumentEditor/tests/jsx/impl.ts
  packages-next/fields-document/src/DocumentEditor/tests/jsx/namespace.d.ts
  packages-next/fields-document/src/DocumentEditor/tests/jsx/namespace.js
  packages-next/fields-document/src/DocumentEditor/tests/test-utils.test.tsx
  packages-next/fields-document/src/DocumentEditor/tests/utils.ts
  packages-next/fields-document/src/DocumentEditor/utils.ts
  packages-next/fields-document/src/component-blocks.tsx
  tsconfig.json
  yarn.lock
Labels: new interfaces

#4304 Use protectIdentities = true by default
  .changeset/loud-eggs-appear.md
  .changeset/many-news-double.md
  .changeset/orange-rabbits-tap.md
  examples/blog/index.js
  examples/meetup/index.js
  packages-next/auth/src/index.ts
  packages/auth-password/README.md
  packages/auth-password/index.js
  packages/create-keystone-app/example-projects/starter/index.js
Labels: new interfaces, review me

#4543 Add API tests for ecommerce custom mutations
  .changeset/gentle-shirts-dress.md
  .github/workflows/tests.yml
  examples-next/ecommerce/mutations.ts
  examples-next/ecommerce/package.json
  examples-next/ecommerce/tests/mutations.test.ts
Labels: new interfaces, review me

#4587 Use keystone.getTypeDefs and keystone.getResolvers
  .changeset/funny-mice-kiss.md
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/types/src/base.ts
  yarn.lock
Labels: review me

#4586 Remove adminMeta from KeystoneSystem
  .changeset/light-chairs-destroy.md
  packages-next/admin-ui/src/system/getAdminMetaSchema.ts
  packages-next/admin-ui/src/templates/home.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages-next/keystone/src/lib/createSystem.ts
  packages-next/types/src/core.ts
Labels: review me

#4588 Use graphql-upload rather than built in Apollo Upload support.
  .changeset/long-seahorses-decide.md
  .changeset/old-chicken-rest.md
  packages-next/keystone/package.json
  packages-next/keystone/src/lib/createExpressServer.ts
  packages-next/keystone/src/lib/createGraphQLSchema.ts
  packages/app-graphql/index.js
  packages/app-graphql/package.json
  packages/fields-cloudinary-image/package.json
  packages/fields/package.json
  packages/fields/src/types/File/README.md
  packages/keystone/lib/Keystone/index.js
  packages/keystone/package.json
  yarn.lock
Labels: review me

#4591 Revert regression in mongoose queries
  .changeset/nice-eggs-accept.md
  packages/adapter-mongoose/lib/query-parser.js
Labels: review me

#4592 Update CI to run on node 14 rather than 10
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: review me

#4593 Test against postgres v12
  .github/workflows/tests.yml
Labels: review me

#4604 Simplify creation of adminMetaRoot
  .changeset/khaki-pots-shout.md
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/system/createAdminMeta.ts
  packages-next/admin-ui/src/system/getAdminMetaSchema.ts
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/fields/src/types/relationship/index.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/core.ts
Labels: new interfaces, review me
