Repository keystonejs/keystone, pull requests merged in 2020-10, with the labels that each got.

#3684 Make GraphQL id field non-nullable on output types
  .changeset/many-carpets-sin.md
  .changeset/neat-impalas-drive.md
  .changeset/twenty-horses-fetch.md
  packages/fields-auto-increment/src/Implementation.js
  packages/fields-mongoid/src/Implementation.js
  packages/fields/src/types/Uuid/Implementation.js
Labels: review me

#3851 Bunch of little things in the new interfaces
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/pagination.tsx
  packages-next/keystone/src/classes/Keystone.ts
Labels: new interfaces

#3852 A bunch more little things in new interfaces
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/useSelectedFields.tsx
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/keystone/src/schema/schema.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/schema/index.ts
Labels: new interfaces

#3856 Update prisma to 2.8.0
  .changeset/proud-beers-wash.md
  packages/adapter-prisma/lib/adapter-prisma.js
  packages/adapter-prisma/package.json
  yarn.lock
Labels: review me

#3859 Handle errors better on list page in new interfaces
  examples-next/basic/keystone.ts
  examples-next/basic/schema.ts
  packages-next/admin-ui/src/components/Navigation.tsx
  packages-next/admin-ui/src/components/SignoutButton.tsx
  packages-next/admin-ui/src/pages/HomePage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/utils/dataGetter.ts
  packages-next/admin-ui/src/utils/getRootFieldsFromSelection.ts
Labels: needs-clarification, new interfaces

#3879 Better errors on item page in new interfaces
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/utils/getRootFieldsFromSelection.ts
Labels: new interfaces

#3880 Rename authentication field to session in access control args in new interfaces
  examples-next/basic/schema.ts
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/keystone/src/lib/createAccessControlContext.ts
  packages-next/types/src/schema/access-control.ts
Labels: new interfaces

#3882 Memoize getRootGraphQLFieldsFromFieldController
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/utils/getRootGraphQLFieldsFromFieldController.ts
Labels: new interfaces

#3883 Create form in new interfaces
  packages-next/admin-ui/src/components/CreateForm.tsx
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/utils/serialization.tsx
Labels: new interfaces

#3884 Update new interfaces Admin UI TODOs
  packages-next/admin-ui/TODO.md
Labels: new interfaces

#3886 Field selection ui in new interfaces
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/pages/ListPage/FieldSelection.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: new interfaces

#3885 Update @types/ deps
  yarn.lock
Labels: needs-clarification, review me

#3890 First pass of filter ui in new interfaces
  design-system/packages/core/src/themes/default.ts
  design-system/packages/core/src/utils.ts
  design-system/packages/fields/src/SelectInput.tsx
  design-system/packages/fields/src/hooks/indicators.ts
  design-system/packages/fields/src/index.ts
  design-system/packages/segmented-control/src/SegmentedControl.tsx
  design-system/website/pages/components/fields.tsx
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ListPage/FilterAdd.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterList.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/useFilters.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/types/src/admin-meta.ts
Labels: new interfaces

#3892 Use pills for filters in new interfaces
  design-system/packages/pill/package.json
  design-system/packages/pill/src/index.tsx
  design-system/website/components/Navigation.tsx
  design-system/website/package.json
  design-system/website/pages/components/pill.tsx
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ListPage/FilterList.tsx
Labels: new interfaces

#3896 New DS - Pill design tweaks
  design-system/packages/pill/src/index.tsx
Labels: new interfaces

#3897 Upping max session age in the basic demo
  examples-next/basic/keystone.ts
Labels: new interfaces

#3889 Make unit tests more parallel to increase throughput
  .github/workflows/tests.yml
Labels: review me

#3902 Add Options component to ds
  design-system/packages/options/package.json
  design-system/packages/options/src/index.tsx
  design-system/website/components/Navigation.tsx
  design-system/website/package.json
  design-system/website/pages/components/options.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterList.tsx
  yarn.lock
Labels: new interfaces, review me

#3903 Add Drawer to DS
  design-system/packages/modals/package.json
  design-system/packages/modals/src/Blanket.tsx
  design-system/packages/modals/src/Drawer.tsx
  design-system/packages/modals/src/DrawerBase.tsx
  design-system/packages/modals/src/DrawerController.tsx
  design-system/packages/modals/src/drawer-context.tsx
  design-system/packages/modals/src/index.tsx
  design-system/packages/modals/src/types.ts
  design-system/website/components/Navigation.tsx
  design-system/website/package.json
  design-system/website/pages/_app.tsx
  design-system/website/pages/components/modals.tsx
  yarn.lock
Labels: new interfaces, review me

#3905 Add AlertDialog
  design-system/packages/modals/src/AlertDialog.tsx
  design-system/packages/modals/src/DialogBase.tsx
  design-system/packages/modals/src/index.tsx
  design-system/website/pages/components/modals.tsx
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: needs-clarification, new interfaces

#3906 Add toasts to DS
  design-system/packages/segmented-control/package.json
  design-system/packages/toast/package.json
  design-system/packages/toast/src/Toast.tsx
  design-system/packages/toast/src/context.tsx
  design-system/packages/toast/src/index.tsx
  design-system/packages/toast/src/types.ts
  design-system/website/components/Navigation.tsx
  design-system/website/package.json
  design-system/website/pages/_app.tsx
  design-system/website/pages/components/toast.tsx
  packages-next/admin-ui/TODO.md
Labels: new interfaces

#3912 CreateItemDrawer in new interfaces
  design-system/packages/modals/src/Drawer.tsx
  examples-next/basic/.keystone/schema-types.ts
  packages-next/admin-ui/src/components/CreateItemDrawer.tsx
  packages-next/admin-ui/src/context.tsx
  packages-next/admin-ui/src/pages/HomePage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/templates/home.ts
  packages-next/auth/src/templates/signin.ts
Labels: new interfaces

#3930 Prepare create-keystone-app for more than two adapters
  .changeset/nine-deers-hide.md
  packages/create-keystone-app/lib/generate-code.js
  packages/create-keystone-app/lib/get-adapter-choice.js
  packages/create-keystone-app/lib/get-adapter-config.js
  packages/create-keystone-app/lib/show-success-message.js
  packages/create-keystone-app/lib/test-adapter-connection.js
Labels: review me

#3929 Use Emotion 11 in new interfaces
  design-system/packages/button/package.json
  design-system/packages/core/package.json
  design-system/packages/core/src/components/Box.tsx
  design-system/packages/core/src/components/Center.tsx
  design-system/packages/core/src/components/Core.tsx
  design-system/packages/core/src/components/Divider.tsx
  design-system/packages/core/src/components/Heading.tsx
  design-system/packages/core/src/components/Inline.tsx
  design-system/packages/core/src/components/Link.tsx
  design-system/packages/core/src/components/Stack.tsx
  design-system/packages/core/src/components/Text.tsx
  design-system/packages/core/src/emotion.ts
  design-system/packages/core/src/index.ts
  design-system/packages/core/src/normalize.ts
  design-system/packages/fields/package.json
  design-system/packages/loading/package.json
  design-system/packages/notice/src/Notice.tsx
  design-system/packages/segmented-control/package.json
  design-system/website/components/Code.tsx
  design-system/website/components/Navigation.tsx
  design-system/website/components/Page.tsx
  design-system/website/components/ReadableColor.tsx
  design-system/website/package.json
  design-system/website/pages/components/button.tsx
  design-system/website/pages/components/fields.tsx
  design-system/website/pages/components/notice.tsx
  design-system/website/pages/core/alias-tokens.tsx
  design-system/website/pages/core/global-tokens.tsx
  design-system/website/pages/core/theme.tsx
  design-system/website/pages/index.tsx
  design-system/website/pages/layout/box.tsx
  design-system/website/pages/layout/center.tsx
  design-system/website/pages/layout/stack.tsx
  examples-next/basic/admin/fieldViews/Content.tsx
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/components/Logo.tsx
  packages-next/admin-ui/src/components/Navigation.tsx
  packages-next/admin-ui/src/components/PageContainer.tsx
  packages-next/admin-ui/src/components/SignoutButton.tsx
  packages-next/auth/package.json
  packages-next/auth/src/components/SigninContainer.tsx
  packages-next/fields/package.json
  yarn.lock
Labels: new interfaces

#3932 Use toasts in new Admin UI
  design-system/packages/toast/src/types.ts
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/context.tsx
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: needs-clarification, new interfaces

#3739 Add support for Prisma to create-keystone-app
  .changeset/flat-pans-greet.md
  docs/guides/prisma.md
  packages/create-keystone-app/lib/generate-code.js
  packages/create-keystone-app/lib/get-adapter-choice.js
  packages/create-keystone-app/lib/get-adapter-config.js
  packages/create-keystone-app/lib/show-success-message.js
  packages/create-keystone-app/lib/test-adapter-connection.js
  packages/create-keystone-app/package.json
Labels: review me

#3934 First pass of moving field selection into popover in new interfaces
  design-system/packages/fields/src/hooks/indicators.ts
  design-system/packages/options/src/index.tsx
  design-system/packages/popover/src/Popover.tsx
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ListPage/FieldSelection.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: needs-clarification, new interfaces

#3937 Note regarding use of schemaName with app-graphql
  packages/app-graphql/README.md
Labels: needs-clarification

#3933 Add label resolver blog post
  docs/blog/better-ux-with-custom-labels.md
Labels: needs-clarification

#3938 Fixing keystone case in label resolver blog example
  docs/blog/better-ux-with-custom-labels.md
Labels: needs-clarification

#3940 Move add filter into popover in new interfaces
  design-system/packages/core/src/components/Heading.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterAdd.tsx
Labels: new interfaces

#3948 Exit the dev process when an error is thrown
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/session/index.ts
  packages-next/keystone/src/static/dev-loading.html
Labels: new interfaces

#3949 First pass of sort selection ui in new interfaces and respect initialSort in config
  examples-next/basic/.keystone/schema-types.ts
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/pages/ListPage/FieldSelection.tsx
  packages-next/admin-ui/src/pages/ListPage/SortSelection.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/useFilters.tsx
  packages-next/admin-ui/src/pages/ListPage/useSelectedFields.tsx
  packages-next/admin-ui/src/pages/ListPage/useSort.tsx
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/admin-meta.ts
Labels: new interfaces

#3950 isHidden admin option in new interfaces
  packages-next/admin-ui/src/components/Navigation.tsx
  packages-next/admin-ui/src/context.tsx
  packages-next/admin-ui/src/pages/HomePage.tsx
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
Labels: new interfaces

#3777 Initial commit of new auth example, including todo + spec
  examples-next/TODO.md
  examples-next/auth/keystone.ts
  examples-next/auth/package.json
  examples-next/auth/schema.ts
  examples-next/basic/keystone.ts
  packages-next/keystone/src/lib/createAdminUIServer.ts
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/session/index.ts
Labels: new interfaces

#3951 Hide auth fields in the Admin UI
  examples-next/auth/schema.ts
  packages-next/auth/src/index.ts
Labels: new interfaces

#3955 Change filter format function in labels to a component in new interfaces to allow for fetching label for relationship field
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/pages/HomePage.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterList.tsx
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/types/src/admin-meta.ts
Labels: new interfaces

#3957 Add integer field to new interfaces
  examples-next/basic/.keystone/schema-types.ts
  examples-next/basic/schema.ts
  packages-next/fields/src/index.ts
  packages-next/fields/src/types/integer/index.ts
  packages-next/fields/src/types/integer/views/index.tsx
  packages-next/fields/types/integer/views/package.json
Labels: new interfaces

#3958 idField option and treating id fields as regular fields in Admin UI in new interfaces
  examples-next/basic/.keystone/schema-types.ts
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/fields/package.json
  packages-next/fields/src/index.ts
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/mongoId/index.ts
  packages-next/fields/src/types/mongoId/views/index.tsx
  packages-next/fields/types/mongoId/views/package.json
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/keystone/src/scripts/schema-type-printer.tsx
  packages-next/types/src/schema/index.ts
Labels: new interfaces

#3959 Remove _label_ GraphQL field in new interfaces with new labelField option specific to the Admin UI
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/components/CreateItemDrawer.tsx
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/FieldSelection.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/useSelectedFields.tsx
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/utils/serialization.tsx
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/schema/index.ts
Labels: new interfaces

#3965 First pass of relationship field view in new interfaces
  design-system/packages/fields/package.json
  design-system/packages/fields/src/Select.tsx
  design-system/packages/fields/src/SelectInput.tsx
  design-system/packages/fields/src/hooks/inputs.ts
  design-system/packages/fields/src/index.ts
  design-system/website/pages/components/fields.tsx
  examples-next/basic/schema.ts
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/FilterAdd.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/integer/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/relationship/views/RelationshipSelect.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#3966 Relationship field view buttons in new interfaces
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: new interfaces

#3977 Password field view and client-side validation in new interfaces
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/components/CreateItemDrawer.tsx
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/password/index.ts
  packages-next/fields/src/types/password/views/index.tsx
Labels: new interfaces

#3978 Select field type in new interfaces
  examples-next/basic/.keystone/schema-types.ts
  examples-next/basic/schema.ts
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/fields/src/index.ts
  packages-next/fields/src/types/select/index.ts
  packages-next/fields/src/types/select/views/index.tsx
  packages-next/fields/types/select/views/package.json
Labels: new interfaces

#3980 Nested create in relationship view in new interfaces
  packages-next/admin-ui/src/components/CreateItemDrawer.tsx
  packages-next/admin-ui/src/components/index.ts
  packages-next/admin-ui/src/context.tsx
  packages-next/admin-ui/src/pages/HomePage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/relationship/views/index.tsx
Labels: new interfaces

#3981 Virtual field in new interfaces
  examples-next/basic/.keystone/schema-types.ts
  examples-next/basic/schema.ts
  packages-next/fields/src/index.ts
  packages-next/fields/src/types/virtual/index.ts
  packages-next/fields/src/types/virtual/views/PrettyData.tsx
  packages-next/fields/src/types/virtual/views/index.tsx
  packages-next/fields/types/virtual/views/package.json
Labels: new interfaces

#3983 docs(prisma): minor changes to the Prisma guide
  docs/guides/prisma.md
Labels: needs-clarification

#3988 Store list page state in local storage in new interfaces
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: new interfaces

#3979 Reshape CI test grouping
  .changeset/yellow-penguins-wonder.md
  .github/workflows/tests.yml
  docs/guides/prisma.md
  packages-next/admin-ui/TODO.md
  packages/app-graphql/README.md
  packages/file-adapters/README.md
  packages/test-utils/lib/test-utils.js
  tests/api-tests/fields/types/AuthedRelationship.test.js
  tests/api-tests/fields/types/CalendarDay.test.js
  tests/api-tests/fields/types/DateTime.test.js
  tests/api-tests/fields/types/Slug.test.js
  tests/api-tests/fields/types/Virtual.test.js
  tests/api-tests/package.json
  tests/api-tests/server-side-graphql-client.test.js
Labels: review me

#3992 displayMode option on text and select field types in new interfaces
  examples-next/basic/schema.ts
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/fields/src/types/select/index.ts
  packages-next/fields/src/types/select/views/index.tsx
  packages-next/fields/src/types/text/index.ts
  packages-next/fields/src/types/text/views/index.tsx
Labels: new interfaces

#3996 Improving Select component styling to fit with the new theme
  design-system/packages/fields/src/Select.tsx
  design-system/packages/fields/src/hooks/inputs.ts
Labels: new interfaces

#4004 Fix unnecessarily refetching static admin meta in new interfaces
  packages-next/admin-ui/src/context.tsx
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
Labels: new interfaces

#4009 Add provider config option to PrismaAdapter
  .changeset/tiny-months-work.md
  packages/adapter-prisma/lib/adapter-prisma.js
  packages/test-utils/lib/test-utils.js
Labels: review me

#4010 Update data type selection in Select fields
  .changeset/spotty-shoes-turn.md
  packages/fields/src/types/Select/Implementation.js
Labels: review me

#4018 Pin gatsby versions
  .changeset/selfish-worms-lie.md
  package.json
  packages/arch/docs/package.json
  website/package.json
  yarn.lock
Labels: review me

#4033 Pin package version to allow yarn.lock clean
  package.json
Labels: review me

#4014 Rename prisma to prisma_postgresql in multiAdapterRunners
  .changeset/red-carpets-kick.md
  .github/workflows/tests.yml
  packages/fields-cloudinary-image/src/test-fixtures.skip.js
  packages/fields-oembed/src/test-fixtures.js
  packages/fields-unsplash/src/test-fixtures.skip.js
  packages/fields/src/types/Decimal/test-fixtures.js
  packages/fields/src/types/File/test-fixtures.js
  packages/test-utils/lib/test-utils.js
Labels: review me

#3904 Enable tests in Json based field types for prisma
  packages/fields-cloudinary-image/src/test-fixtures.skip.js
  packages/fields-oembed/src/test-fixtures.js
  packages/fields-unsplash/src/test-fixtures.skip.js
  packages/fields/src/types/File/test-fixtures.js
Labels: review me

#4052 Save vertical space in test code
  packages/fields-content/src/test-fixtures.js
Labels: review me

#4072 Misc cleanup in new interfaces
  design-system/website/next.config.js
  packages-next/admin-ui/package.json
  packages-next/admin-ui/static/next.config.js
  packages-next/fields/src/types/password/index.ts
  packages-next/keystone/src/classes/Keystone.ts
Labels: new interfaces

#4068 Updating TODOs
  packages-next/TODO.md
  packages-next/admin-ui/TODO.md
Labels: new interfaces

#4073 More todo items for keystone-next alpha release
  packages-next/TODO.md
Labels: new interfaces

#4080 First pass of small fixes in preparation for publishing new interfaces
  packages-next/TODO.md
  packages-next/fields/src/types/virtual/index.ts
  packages-next/fields/src/types/virtual/views/index.tsx
  packages-next/keystone/src/lib/initKeystoneFromConfig.ts
Labels: new interfaces

#4081 Various Admin UI new interfaces fixes
  packages-next/TODO.md
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/components/CreateItemDrawer.tsx
  packages-next/admin-ui/src/components/GraphQLErrorNotice.tsx
  packages-next/admin-ui/src/components/index.ts
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/auth/package.json
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/timestamp/views/index.tsx
Labels: new interfaces

#4083 Small new interfaces fixes for publishing
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/keystone/src/scripts/dev.ts
Labels: new interfaces

#4084 Get around a rollup bug in the new interfaces
  packages-next/admin-ui/src/apollo.tsx
  packages-next/admin-ui/src/router.tsx
Labels: new interfaces

#4085 Only work around Rollup bug for router entrypoint in new interfaces
  packages-next/admin-ui/src/apollo.tsx
  packages-next/admin-ui/src/router.tsx
Labels: new interfaces

#4074 Rename existingItem argument to item for access control functions
  examples-next/auth/schema.ts
  packages-next/keystone/src/lib/createAccessControlContext.ts
  packages-next/types/src/schema/access-control.ts
Labels: new interfaces

#4087 Rename session.item to session.data
  examples-next/auth/schema.ts
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/keystone/src/session/index.ts
Labels: new interfaces

#4088 Make field config optional where possible
  packages-next/fields/src/types/autoIncrement/index.ts
  packages-next/fields/src/types/checkbox/index.ts
  packages-next/fields/src/types/integer/index.ts
  packages-next/fields/src/types/password/index.ts
  packages-next/fields/src/types/text/index.ts
  packages-next/fields/src/types/timestamp/index.ts
Labels: new interfaces

#4090 Move createKeystone to lib
  packages-next/TODO.md
  packages-next/keystone/src/index.ts
  packages-next/keystone/src/lib/createKeystone.ts
  packages-next/keystone/src/lib/initKeystoneFromConfig.ts
Labels: new interfaces
