Repository keystonejs/keystone, pull requests merged in 2020-09, with the labels that each got.

#3509 Remove unused dependencies
  .changeset/fair-lies-push.md
  api-tests/package.json
  test-projects/client-validation/package.json
Labels: needs-clarification, review me

#3553 Add API tests for CloudinaryImage field type
  .changeset/tiny-rockets-lick.md
  .github/workflows/tests.yml
  packages/fields-cloudinary-image/.env.example
  packages/fields-cloudinary-image/package.json
  packages/fields-cloudinary-image/src/test-files/graphql.jpeg
  packages/fields-cloudinary-image/src/test-files/keystone.jpeg
  packages/fields-cloudinary-image/src/test-files/react.jpeg
  packages/fields-cloudinary-image/src/test-files/thinkmill.jpeg
  packages/fields-cloudinary-image/src/test-fixtures.js
Labels: review me

#3550 Remove unused dependencies
  .changeset/shaggy-items-reflect.md
  packages/adapter-knex/package.json
  packages/adapter-mongoose/package.json
  packages/app-graphql-playground/package.json
  packages/app-graphql/package.json
Labels: review me

#3565 Add more tests for 1:1 create operations
  .changeset/breezy-deers-look.md
  docs/blog/field-types.md
  tests/api-tests/relationships/crud/one-to-one.test.js
Labels: needs-clarification, review me

#3569 Add missing logging plugin in the docs
  .changeset/swift-worms-relate.md
  packages/list-plugins/logging.md
Labels: review me

#3532 Consolidate field filter tests
  .changeset/many-owls-tickle.md
  packages/fields-auto-increment/src/test-fixtures.js
  packages/fields-cloudinary-image/package.json
  packages/fields-cloudinary-image/src/test-files/thinkmill1.jpeg
  packages/fields-cloudinary-image/src/test-files/thinkmill2.jpeg
  packages/fields-cloudinary-image/src/test-fixtures.js
  packages/fields-color/src/test-fixtures.js
  packages/fields-location-google/package.json
  packages/fields-location-google/src/test-fixtures.js
  packages/fields-markdown/src/test-fixtures.js
  packages/fields-mongoid/package.json
  packages/fields-mongoid/src/Implementation.js
  packages/fields-mongoid/src/test-fixtures.js
  packages/fields-oembed/package.json
  packages/fields-oembed/src/test-fixtures.js
  packages/fields-unsplash/package.json
  packages/fields-unsplash/src/test-fixtures.js
  packages/fields-wysiwyg-tinymce/package.json
  packages/fields-wysiwyg-tinymce/src/test-fixtures.js
  packages/fields/src/types/CalendarDay/test-fixtures.js
  packages/fields/src/types/Checkbox/test-fixtures.js
  packages/fields/src/types/DateTime/test-fixtures.js
  packages/fields/src/types/DateTimeUtc/test-fixtures.js
  packages/fields/src/types/Decimal/Implementation.js
  packages/fields/src/types/Decimal/test-fixtures.js
  packages/fields/src/types/File/test-files/thinkmill1.jpeg
  packages/fields/src/types/File/test-files/thinkmill2.jpeg
  packages/fields/src/types/File/test-fixtures.js
  packages/fields/src/types/Float/test-fixtures.js
  packages/fields/src/types/Integer/test-fixtures.js
  packages/fields/src/types/Password/test-fixtures.js
  packages/fields/src/types/Select/test-fixtures.js
  packages/fields/src/types/Text/test-fixtures.js
  packages/fields/src/types/Url/test-fixtures.js
  packages/fields/src/types/Uuid/Implementation.js
  packages/fields/src/types/Uuid/test-fixtures.js
  packages/fields/tests/test-fixtures.js
  tests/api-tests/fields/filter.test.js
Labels: review me

#3587 Remove unused dependency
  .changeset/smooth-queens-taste.md
  packages/fields-unsplash/package.json
Labels: needs-clarification, review me

#3606 Remove unused dependencies
  .changeset/early-apples-beam.md
  examples/blog/package.json
  packages/fields-cloudinary-image/package.json
  packages/fields/package.json
Labels: needs-clarification, review me

#3616 Fix bug with count null queries on 1:1 rels
  .changeset/nasty-rules-call.md
  packages/adapter-knex/lib/adapter-knex.js
  tests/api-tests/relationships/crud-self-ref/one-to-one.test.js
  tests/api-tests/relationships/crud/many-to-many-one-sided.test.js
  tests/api-tests/relationships/crud/many-to-many.test.js
  tests/api-tests/relationships/crud/one-to-one.test.js
  tests/api-tests/relationships/filtering/nested.test.js
Labels: review me

#3555 update website ia
  website/gatsby-node.js
  website/src/components/Sidebar.js
  website/src/components/SidebarBlog.js
  website/src/components/homepage/SectionHero.js
  website/src/pages/api.js
  website/src/pages/documentation.js
  website/src/templates/apiHome.js
  website/src/templates/blogPost.js
  website/src/templates/docs.js
  website/src/templates/layout.js
  website/src/templates/listPage.js
  website/src/utils/hooks.js
  website/src/utils/nav-data-blog.js
Labels: needs-clarification

#3622 Remove unused skipRequiredTest flag
  .changeset/four-candles-fry.md
  packages/fields-location-google/src/test-fixtures.js
  packages/fields-unsplash/src/test-fixtures.js
Labels: review me

#3629 Remove native type mapping
  .changeset/giant-brooms-drop.md
  packages/fields-authed-relationship/README.md
  packages/fields-authed-relationship/src/tests/index.test.js
  packages/fields-location-google/src/test-fixtures.skip.js
  packages/fields/README.md
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/lib/ListTypes/utils.js
  packages/keystone/tests/List.test.js
  packages/server-side-graphql-client/README.md
Labels: review me

#3633 use @manypkg/get-packages instead of get-workspaces
  website/gatsby-config.js
  website/package.json
Labels: needs-clarification

#3630 Deprecate @keystonejs/logging
  .changeset/swift-maps-wonder.md
  packages/logger/README.md
Labels: review me

#3632 Deprecate @keystonejs/mongo-join-builder package
  .changeset/funny-keys-own.md
  packages/mongo-join-builder/README.md
Labels: review me

#3637 Fix pagination bug in getItems
  .changeset/afraid-days-rest.md
  packages/server-side-graphql-client/lib/server-side-graphql-client.js
  packages/server-side-graphql-client/tests/index.test.js
Labels: needs-clarification, review me

#3634 Remove @keystonejs/logger package
  packages/keystone/lib/Keystone/format-error.js
  packages/keystone/lib/Keystone/logger.js
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/lib/providers/custom.js
  packages/keystone/lib/providers/listAuth.js
  packages/keystone/package.json
  packages/keystone/tests/List.test.js
  packages/logger/.npmignore
  packages/logger/CHANGELOG.md
  packages/logger/README.md
  packages/logger/index.js
  packages/logger/lib/logger.js
  packages/logger/package.json
Labels: review me

#3631 Merge mongo-join-builder code into adapter-mongoose
  package.json
  packages/adapter-mongoose/lib/adapter-mongoose.js
  packages/adapter-mongoose/lib/join-builder.js
  packages/adapter-mongoose/lib/query-parser.js
  packages/adapter-mongoose/lib/tokenizers.js
  packages/adapter-mongoose/package.json
  packages/adapter-mongoose/tests/index.test.js
  packages/adapter-mongoose/tests/join-builder.test.js
  packages/adapter-mongoose/tests/mongo-results.test.js
  packages/adapter-mongoose/tests/query-parser.test.js
  packages/adapter-mongoose/tests/relationship-path.test.js
  packages/adapter-mongoose/tests/relationship.test.js
  packages/adapter-mongoose/tests/simple.test.js
  packages/adapter-mongoose/tests/utils.js
  packages/mongo-join-builder/.npmignore
  packages/mongo-join-builder/CHANGELOG.md
  packages/mongo-join-builder/README.md
  packages/mongo-join-builder/examples/database.js
  packages/mongo-join-builder/examples/nested-relationship/index.js
  packages/mongo-join-builder/examples/relationship/index.js
  packages/mongo-join-builder/index.js
  packages/mongo-join-builder/package.json
Labels: review me

#3645 Add missing changesets
  .changeset/kind-badgers-thank.md
  .changeset/silly-mails-accept.md
Labels: review me

#3660 incremental blog improvements
  docs/blog/field-types.md
  docs/blog/introduction-to-graphql.md
  website/gatsby-node.js
  website/src/components/BlogMeta.js
  website/src/templates/docs.js
  website/src/templates/listPage.js
Labels: review me

#3654 add knex example
  examples/meetup/README.md
  examples/todo-knex/.gitignore
  examples/todo-knex/README.md
  examples/todo-knex/index.js
  examples/todo-knex/package.json
  examples/todo-knex/public/index.html
  examples/todo/README.md
Labels: examples, review me

#3673 Add more field tests for Slug field type
  .changeset/grumpy-pants-argue.md
  docs/blog/introduction-to-graphql.md
  packages/fields/src/types/Slug/test-fixtures.js
  packages/fields/src/types/Slug/test-fixtures.skip.js
  tests/api-tests/fields/crud.test.js
  tests/api-tests/fields/unique.test.js
Labels: review me

#3674 Move from @apollo/react-components to @apollo/client
  .changeset/honest-seas-eat.md
  packages/apollo-helpers/package.json
  packages/apollo-helpers/src/index.js
  yarn.lock
Labels: needs-clarification, review me

#3678 Remove unused dependency
  .changeset/eleven-bananas-cry.md
  .changeset/olive-years-push.md
  packages/adapter-mongoose/package.json
  packages/fields/package.json
Labels: needs-clarification, review me

#3679 Update dependency cypress-file-upload to v4
  .changeset/proud-files-cover.md
  packages/app-admin-ui/README.md
  tests/test-projects/access-control/cypress/support/commands.js
  tests/test-projects/access-control/package.json
  tests/test-projects/basic/cypress/integration/local-file-upload_spec.js
  tests/test-projects/basic/cypress/support/commands.js
  tests/test-projects/basic/package.json
  tests/test-projects/client-validation/cypress/support/commands.js
  tests/test-projects/login/cypress/support/commands.js
  tests/test-projects/login/package.json
  yarn.lock
Labels: review me

#3685 Remove unused dependency of @keystonejs/fields from @keystonejs/keystone
  .changeset/loud-melons-bow.md
  packages/keystone/package.json
Labels: review me

#3693 Remove dependency on pluralize
  .changeset/olive-avocados-lick.md
  packages/fields-cloudinary-image/package.json
  packages/fields-cloudinary-image/src/ImageBlock.js
  packages/fields-cloudinary-image/src/views/blocks/single-image.js
  packages/fields-oembed/package.json
  packages/fields-oembed/src/OEmbedBlock.js
  packages/fields-oembed/src/views/blocks/oembed.js
  packages/fields-unsplash/package.json
  packages/fields-unsplash/src/UnsplashBlock.js
  packages/fields-unsplash/src/views/blocks/unsplash-image.js
Labels: needs-clarification, review me

#3696 Disable cloudinary API tests
  .changeset/tough-boxes-knock.md
  packages/fields-cloudinary-image/src/test-fixtures.skip.js
Labels: needs-clarification, review me

#3695 website: Fix mobile homepage UI issue
  website/src/components/homepage/SectionHero.js
Labels: needs-clarification

#3712 Skip running tests if no relevant files are changed
  .github/workflows/tests.yml
Labels: needs-clarification, review me

#3714 cornice release blog
  docs/blog/new-release-cornice.md
Labels: needs-clarification

#3718 Auto approve PRs from base repo that only change new interfaces
  .github/workflows/auto-approve.yml
Labels: new interfaces

#3723 Essentially disable paths-filter to unblock CI for now
  .github/workflows/auto-approve.yml
  .github/workflows/tests.yml
Labels: needs-clarification

#3722 Skip netlify builds when unnecessary
  netlify.toml
Labels: review me

#3726 Fix paths-filter to only run twice per commit rather than _a lot_ to prevent rate limiting
  .github/workflows/auto-approve.yml
  .github/workflows/tests.yml
Labels: review me

#3738 Fix CI failing on master
  .github/workflows/tests.yml
Labels: needs-clarification

#3740 Improve logic readability in knex adapter
  .changeset/breezy-pets-matter.md
  docs/guides/intro-to-graphql.md
  examples/todo-knex/CHANGELOG.md
  packages-next/keystone/CHANGELOG.md
  packages/adapter-knex/lib/adapter-knex.js
Labels: review me

#3741 Add an idPath to relationship field adapters
  .changeset/light-pears-smile.md
  packages/fields/src/types/Relationship/Implementation.js
Labels: review me

#3745 New interfaces: Adding as prop support to Button
  design-system/packages/button/src/Button.tsx
  packages-next/admin-ui/src/components/Navigation.tsx
  packages-next/admin-ui/src/pages/HomePage.tsx
Labels: new interfaces

#3744 Test AutoIncrement as both an ID and Int graphQL type
  packages/fields-auto-increment/src/test-fixtures.js
  tests/api-tests/fields/filter.test.js
Labels: review me

#3746 New Interfaces: Implementing signout button in Navigation
  packages-next/admin-ui/src/components/Navigation.tsx
Labels: needs-clarification

#3752 Remove unused @preconstruct/hook dependency
  packages-next/keystone/package.json
  yarn.lock
Labels: needs-clarification, review me

#3753 First pass of field selection in new interfaces
  packages-next/admin-ui/src/pages/ListPage.tsx
  packages-next/admin-ui/src/router.tsx
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/fields/package.json
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#3757 New interfaces Admin UI filters
  packages-next/admin-ui/src/pages/ListPage.tsx
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/relationship/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/types/src/index.ts
Labels: needs-clarification, new interfaces

#3759 Styling the new List UI
  packages-next/admin-ui/src/pages/ListPage.tsx
Labels: new interfaces

#3761 Adding fields TODO
  packages-next/fields/TODO.md
Labels: new interfaces

#3771 Sorting in new Admin UI
  examples-next/basic/schema.ts
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#3760 In renovate, skip remark and gatsby repos
  renovate.json
Labels: needs-clarification

#3758 withItemData now mostly works
  examples-next/basic/keystone.ts
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/components/Navigation.tsx
  packages-next/admin-ui/src/components/SignoutButton.tsx
  packages-next/admin-ui/src/pages/NoAccessPage.tsx
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/templates/no-access.ts
  packages-next/admin-ui/src/utils/useAuthenticatedItem.tsx
  packages-next/admin-ui/static/no-access.js
  packages-next/auth/TODO.md
  packages-next/auth/src/index.ts
  packages-next/auth/src/initFirstItemSchemaExtension.ts
  packages-next/auth/src/types.ts
  packages-next/keystone/package.json
  packages-next/keystone/session/package.json
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/keystone/src/lib/startAdminUI.ts
  packages-next/keystone/src/schema/index.ts
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/index.ts
  packages-next/types/src/session.ts
Labels: new interfaces

#3772 Adding Cell components for use in Fields
  packages-next/admin-ui/components/package.json
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/components/CellContainer.tsx
  packages-next/admin-ui/src/components/CellLink.tsx
  packages-next/admin-ui/src/components/index.ts
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
Labels: new interfaces

#3773 Fix invalid sessions breaking the new admin ui
  packages-next/keystone/src/session/index.ts
Labels: needs-clarification, new interfaces

#3774 Updating types for fieldMode
  examples-next/basic/schema.ts
  packages-next/types/src/index.ts
  packages-next/types/src/schema/index.ts
Labels: new interfaces

#3783 Select items in new Admin UI
  design-system/packages/fields/src/index.ts
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: new interfaces

#3784 Deleting selected items in new admin ui
  design-system/packages/button/src/Button.tsx
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/components/SignoutButton.tsx
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/auth/src/pages/SigninPage.tsx
Labels: needs-clarification, new interfaces

#3787 Make new field views entrypoints
  packages-next/fields/package.json
  packages-next/fields/src/resolve-view.ts
  packages-next/fields/src/types/checkbox/index.ts
  packages-next/fields/src/types/password/index.ts
  packages-next/fields/src/types/relationship/index.ts
  packages-next/fields/src/types/text/index.ts
  packages-next/fields/src/types/timestamp/index.ts
  packages-next/fields/types/checkbox/views/package.json
  packages-next/fields/types/password/views/package.json
  packages-next/fields/types/relationship/views/package.json
  packages-next/fields/types/text/views/package.json
  packages-next/fields/types/timestamp/views/package.json
Labels: new interfaces

#3789 Add support for small and large checkboxes and radio buttons
  design-system/packages/core/src/themes/default.ts
  design-system/packages/fields/src/Checkbox.tsx
  design-system/packages/fields/src/Radio.tsx
  design-system/packages/fields/src/components/ControlLabel.tsx
  design-system/packages/fields/src/components/Icons.tsx
  design-system/packages/fields/src/hooks/indicators.ts
  design-system/website/pages/components/fields.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: new interfaces

#3800 Fix selecting text in segmented control
  design-system/packages/segmented-control/src/SegmentedControl.tsx
Labels: new interfaces

#3806 Regenerate prisma client on schema change
  .changeset/lemon-wolves-relax.md
  packages/adapter-prisma/lib/adapter-prisma.js
Labels: needs-clarification, review me

#3811 docs(prisma-adapter): minor improvements
  packages/adapter-prisma/README.md
Labels: needs-clarification

#3809 Format docs
  design-system/website/CHANGELOG.md
  docs/guides/intro-to-graphql.md
  packages-next/fields/CHANGELOG.md
  packages-next/fields/TODO.md
Labels: review me

#3821 Fix empty queries in prisma adapter
  .changeset/mean-trees-turn.md
  packages/adapter-prisma/lib/adapter-prisma.js
  tests/api-tests/queries/search.test.js
Labels: review me

#3823 CRUD API for schema extensions in new interfaces
  examples-next/basic/.gitignore
  examples-next/basic/.keystone/schema-types.ts
  examples-next/basic/schema.ts
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/keystone/src/lib/crud-api.ts
  packages-next/keystone/src/lib/generateAdminUI.ts
  packages-next/keystone/src/lib/getCoerceAndValidateArgumentsFnForGraphQLField.ts
  packages-next/keystone/src/scripts/dev.ts
  packages-next/keystone/src/session/index.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#3788 Add docs for prisma adapter
  .changeset/little-pumpkins-greet.md
  docs/blog/prisma-adapter.md
  docs/discussions/prisma.md
  docs/guides/prisma.md
  packages/adapter-knex/README.md
  packages/adapter-knex/build-test-db.sh
  packages/adapter-prisma/README.md
Labels: adapters, docs, review me

#3827 More structured fetch of admin meta for Admin UI in new interfaces
  examples-next/basic/.keystone/schema-types.ts
  packages-next/admin-ui/package.json
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/admin-ui/src/templates/app.ts
  packages-next/admin-ui/src/templates/index.ts
  packages-next/admin-ui/src/utils/useAdminMeta.tsx
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/index.ts
Labels: new interfaces

#3828 Fix not redirecting to no access page on signin or init item when the user has no access in new interfaces
  packages-next/auth/src/pages/InitPage.tsx
  packages-next/auth/src/pages/SigninPage.tsx
Labels: new interfaces

#3836 Use fieldModes, hideDelete and hideCreate in new interfaces
  examples-next/basic/schema.ts
  packages-next/admin-ui/src/admin-meta-graphql.ts
  packages-next/admin-ui/src/pages/ItemPage.tsx
  packages-next/admin-ui/src/pages/ListPage/index.tsx
  packages-next/admin-ui/src/pages/ListPage/useSelectedFields.tsx
  packages-next/admin-ui/src/templates/adminMetaSchemaExtension.ts
  packages-next/fields/src/types/checkbox/views/index.tsx
  packages-next/fields/src/types/password/views/index.tsx
  packages-next/fields/src/types/text/views/index.tsx
  packages-next/fields/src/types/timestamp/views/index.tsx
  packages-next/keystone/src/classes/Keystone.ts
  packages-next/types/src/admin-meta.ts
  packages-next/types/src/index.ts
  packages-next/types/src/schema/index.ts
Labels: new interfaces

#3839 Add popover to design system
  design-system/packages/core/package.json
  design-system/packages/core/src/utils.ts
  design-system/packages/notice/package.json
  design-system/packages/popover/package.json
  design-system/packages/popover/src/Popover.tsx
  design-system/packages/popover/src/index.ts
  design-system/website/components/Navigation.tsx
  design-system/website/package.json
  design-system/website/pages/components/popover.tsx
Labels: needs-clarification

#3838 noviny/fix 3413
  .changeset/kind-pillows-cheat.md
  .changeset/rare-jeans-remain.md
  packages/fields-content/src/views/editor/Image.js
  packages/fields-content/src/views/editor/add-block.js
Labels: bug, review me

#3844 More TODO items for the new Admin UI
  packages-next/admin-ui/TODO.md
Labels: new interfaces

#3845 Improved list styles in new Admin UI (column widths, link icon, etc)
  design-system/packages/fields/src/Checkbox.tsx
  design-system/packages/icons/src/Icon.tsx
  packages-next/admin-ui/TODO.md
  packages-next/admin-ui/src/pages/ListPage/index.tsx
Labels: needs-clarification, new interfaces
