Repository keystonejs/keystone, pull requests merged in 2020-08, with the labels that each got.

#3319 Only provide updateAuthed mutation if updates are supported on the list
  .changeset/modern-oranges-sneeze.md
  api-tests/access-control/utils.js
  docs/discussions/database-schema.md
  packages/keystone/lib/providers/listAuth.js
Labels: bug, review me

#3313 Use createItem in api-tests
  .changeset/smooth-planes-fly.md
  api-tests/DateTime.test.js
  api-tests/access-control/authed.test.js
  api-tests/queries/cache-hints.test.js
  api-tests/queries/limits.test.js
  api-tests/queries/relationships.test.js
  api-tests/queries/search.test.js
  api-tests/relationships/filtering/access-control.test.js
  api-tests/relationships/filtering/filtering.test.js
  api-tests/relationships/filtering/nested.test.js
  api-tests/relationships/nested-mutations/connect-many.test.js
  api-tests/relationships/nested-mutations/connect-singular.test.js
  api-tests/relationships/nested-mutations/create-and-connect-many.test.js
  api-tests/relationships/nested-mutations/create-many.test.js
  api-tests/relationships/nested-mutations/create-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-all-many.test.js
  api-tests/relationships/nested-mutations/disconnect-all-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-many.test.js
  api-tests/relationships/nested-mutations/disconnect-singular.test.js
  api-tests/relationships/nested-mutations/reconnect-many-to-one.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
Labels: needs-clarification, review me

#3326 Replace calls to graphqlRequest with keystone.executeGraphQL
  .changeset/fresh-eagles-sniff.md
  api-tests/CalendarDay.test.js
  api-tests/DateTime.test.js
  api-tests/Virtual.test.js
  api-tests/access-control/schema.test.js
  api-tests/default-value/defaults.test.js
  api-tests/extend-graphql-schema/extend-graphql-schema.test.js
  api-tests/hooks/list-hooks.test.js
  api-tests/queries-access-control/meta.test.js
  api-tests/queries/limits.test.js
  api-tests/queries/meta.test.js
  api-tests/queries/relationships.test.js
  api-tests/queries/search.test.js
  api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/many-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  api-tests/relationships/crud-self-ref/one-to-many.test.js
  api-tests/relationships/crud-self-ref/one-to-one.test.js
  api-tests/relationships/crud/many-to-many-one-sided.test.js
  api-tests/relationships/crud/many-to-many.test.js
  api-tests/relationships/crud/one-to-many-one-sided.test.js
  api-tests/relationships/crud/one-to-many.test.js
  api-tests/relationships/crud/one-to-one.test.js
  api-tests/relationships/filtering/filtering.test.js
  api-tests/relationships/filtering/nested.test.js
  api-tests/relationships/nested-mutations/connect-many.test.js
  api-tests/relationships/nested-mutations/connect-singular.test.js
  api-tests/relationships/nested-mutations/create-and-connect-many.test.js
  api-tests/relationships/nested-mutations/create-and-connect-singular.test.js
  api-tests/relationships/nested-mutations/create-many.test.js
  api-tests/relationships/nested-mutations/create-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-all-many.test.js
  api-tests/relationships/nested-mutations/disconnect-all-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-many.test.js
  api-tests/relationships/nested-mutations/disconnect-singular.test.js
  api-tests/relationships/nested-mutations/reconnect-many-to-one.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-one-required.test.js
  api-tests/required.test.js
  api-tests/uniqueness/unique.test.js
Labels: review me

#3328 Use deleteItem in API tests
  .changeset/thin-cars-matter.md
  api-tests/access-control/authed.test.js
Labels: review me

#3329 Use updateItems in API tests
  .changeset/three-cups-walk.md
  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
Labels: review me

#3317 Alert user before closing the createItemModal form
  .changeset/purple-knives-cough.md
  packages/app-admin-ui/client/components/CreateItemModal.js
  test-projects/basic/cypress/integration/create-buttons_spec.js
Labels: review me

#3336 Cosmetic changes to api-tests
  api-tests/relationships/nested-mutations/connect-many.test.js
  api-tests/relationships/nested-mutations/connect-singular.test.js
  api-tests/relationships/nested-mutations/create-and-connect-many.test.js
  api-tests/relationships/nested-mutations/create-and-connect-singular.test.js
  api-tests/relationships/nested-mutations/create-many.test.js
  api-tests/relationships/nested-mutations/create-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-all-many.test.js
  api-tests/relationships/nested-mutations/disconnect-all-singular.test.js
  api-tests/relationships/nested-mutations/disconnect-many.test.js
  api-tests/relationships/nested-mutations/disconnect-singular.test.js
  api-tests/relationships/nested-mutations/reconnect-many-to-one.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
  api-tests/relationships/nested-mutations/two-way-backreference/to-one-required.test.js
Labels: review me

#3332 Add tests and fix bug in byTracking plugin
  .changeset/swift-lobsters-hide.md
  packages/list-plugins/lib/tracking/atTracking.js
  packages/list-plugins/lib/tracking/byTracking.js
  packages/list-plugins/lib/tracking/index.test.js
Labels: review me

#3334 Added an example on how to populate a relationship field in createItem
  packages/server-side-graphql-client/README.md
Labels: needs-clarification

#3308 Move fields-datetime-utc into fields
  .changeset/brave-rocks-give.md
  package.json
  packages/fields-datetime-utc/index.js
  packages/fields-datetime-utc/package.json
  packages/fields/README.md
  packages/fields/src/index.js
  packages/fields/src/types/DateTimeUtc/Implementation.js
  packages/fields/src/types/DateTimeUtc/README.md
  packages/fields/src/types/DateTimeUtc/index.js
  packages/fields/src/types/DateTimeUtc/test-fixtures.js
Labels: review me

#3356 Return logged out user info from session manager
  .changeset/gorgeous-meals-argue.md
  packages/session/lib/session.js
Labels: review me

#3305 Move the location to fields-location-google
  .changeset/eight-dogs-pay.md
  demo-projects/meetup/package.json
  package.json
  packages/app-admin-ui/package.json
  packages/fields-location-google/CHANGELOG.md
  packages/fields-location-google/README.md
  packages/fields-location-google/package.json
  packages/fields-location-google/src/Implementation.js
  packages/fields-location-google/src/index.js
  packages/fields-location-google/src/test-fixtures.js
  packages/fields-location-google/src/views/Cell.js
  packages/fields-location-google/src/views/Controller.js
  packages/fields-location-google/src/views/Field.js
  packages/fields-location-google/views/Cell/package.json
  packages/fields-location-google/views/Controller/package.json
  packages/fields-location-google/views/Field/package.json
  packages/fields/README.md
  packages/fields/package.json
  packages/fields/src/index.js
  packages/fields/src/types/Location/index.js
  yarn.lock
Labels: review me

#3371 Add filter tests for DateTimeUtc
  .changeset/ninety-ladybugs-flow.md
  packages/fields/src/types/DateTimeUtc/test-fixtures.js
Labels: needs-clarification

#3373 Remove global variables
  .changeset/yellow-ways-mix.md
  packages/fields-location-google/src/Implementation.js
  packages/fields/src/types/File/Implementation.js
  packages/fields/src/types/Relationship/Implementation.js
Labels: review me

#3374 Clean up Slug unique value generation
  .changeset/cool-flies-bake.md
  packages/fields/package.json
  packages/fields/src/types/Slug/Implementation.js
Labels: review me

#3375 Add filter tests to URL field type
  .changeset/slow-bananas-flow.md
  packages/fields/src/types/Url/test-fixtures.js
Labels: needs-clarification

#3378 Refactor the slug type tests
  .changeset/wise-zoos-tickle.md
  packages/fields/src/types/Slug/Implementation.test.js
Labels: review me

#3379 Refactor default value tests
  .changeset/twelve-boxes-know.md
  api-tests/default-value/defaults.test.js
Labels: review me

#3383 Update the ssgc tests to have stable ordering
  .changeset/many-eagles-tickle.md
  packages/server-side-graphql-client/tests/index.test.js
Labels: needs-clarification

#3384 fix missing return fields in the initial-data doc
  docs/tutorials/initial-data.md
Labels: needs-clarification

#3391 Remove mock classes from test-utils
  .changeset/rotten-shrimps-allow.md
  packages/fields/src/types/CalendarDay/Implementation.test.js
  packages/keystone/tests/List.test.js
  packages/test-utils/index.js
  packages/test-utils/lib/test-utils.js
Labels: review me

#3400 Restrict mongoose version range
  .changeset/funny-ants-hunt.md
  packages/adapter-mongoose/package.json
  packages/fields-location-google/package.json
  packages/fields/package.json
  yarn.lock
Labels: review me

#3403 GitHub Actions for CI
  .circleci/config.yml
  .circleci/run-or-bail.js
  .github/workflows/release.yml
  .github/workflows/tests.yml
  README.md
  api-tests/relationships/filtering/nested.test.js
  jest-sequencer.js
  package.json
Labels: review me

#3406 Make Actions CI run on master and PRs
  .github/workflows/tests.yml
Labels: needs-clarification

#3394 Convert field getters into methods
  .changeset/honest-tomatoes-laugh.md
  packages/fields-auto-increment/src/Implementation.js
  packages/fields-location-google/src/Implementation.js
  packages/fields-mongoid/src/Implementation.js
  packages/fields-oembed/src/Implementation.js
  packages/fields-unsplash/src/Implementation.js
  packages/fields/src/Implementation.js
  packages/fields/src/types/CalendarDay/Implementation.js
  packages/fields/src/types/Checkbox/Implementation.js
  packages/fields/src/types/DateTime/Implementation.js
  packages/fields/src/types/DateTimeUtc/Implementation.js
  packages/fields/src/types/Decimal/Implementation.js
  packages/fields/src/types/File/Implementation.js
  packages/fields/src/types/Float/Implementation.js
  packages/fields/src/types/Integer/Implementation.js
  packages/fields/src/types/Password/Implementation.js
  packages/fields/src/types/Relationship/Implementation.js
  packages/fields/src/types/Relationship/tests/implementation.test.js
  packages/fields/src/types/Select/Implementation.js
  packages/fields/src/types/Text/Implementation.js
  packages/fields/src/types/Uuid/Implementation.js
  packages/fields/tests/Implementation.test.js
  packages/keystone/lib/ListTypes/list.js
  packages/keystone/tests/Keystone.test.js
  packages/keystone/tests/List.test.js
Labels: review me

#3404 Add filter & CRUD tests for Color field
  .changeset/shiny-countries-remain.md
  api-tests/fields.test.js
  packages/fields-color/package.json
  packages/fields-color/src/test-fixtures.js
Labels: review me

#3409 Fix incorrect graphQL generation
  .changeset/itchy-hounds-rescue.md
  packages/fields/src/types/Relationship/Implementation.js
  packages/fields/src/types/Relationship/tests/implementation.test.js
Labels: review me

#3408 Setup TypeScript things
  .changeset/hungry-ants-live.md
  .eslintrc.js
  .github/workflows/tests.yml
  babel.config.js
  docs/api/hooks.md
  docs/guides/production.md
  docs/guides/relationship-migration.md
  package.json
  packages/app-admin-ui/client/components/Nav.js
  packages/app-admin-ui/client/pages/List/Filters/AddFilterPopout.js
  packages/app-admin-ui/index.js
  packages/app-admin-ui/server/getWebpackConfig.js
  packages/arch/packages/alert/README.md
  packages/arch/packages/hooks/src/index.ts
  packages/fields-wysiwyg-tinymce/src/views/Field.js
  packages/fields/src/types/Relationship/README.md
  tsconfig.json
  website/src/components/Button.js
  website/src/components/Header.js
  website/src/components/markdown/Table.js
  website/src/pages/404.js
  yarn.lock
Labels: review me

#3410 Add filter & Crud tests for Markdown field
  .changeset/fast-lemons-wave.md
  packages/fields-markdown/package.json
  packages/fields-markdown/src/test-fixtures.js
Labels: needs-clarification

#3412 Sort test results before comparing
  .changeset/eighty-rats-check.md
  api-tests/access-control/authed.test.js
Labels: needs-clarification, review me

#3414 Remove the obsolete field-content code from the repo
  packages/field-content/CHANGELOG.md
  packages/field-content/index.js
  packages/field-content/package.json
Labels: review me

#3417 Fix CI not running on Release PR
  .github/workflows/release.yml
Labels: needs-clarification, review me

#3421 Remove .md files from the prettier checks, as remark lints these files
  docs/api/hooks.md
  docs/guides/production.md
  docs/guides/relationship-migration.md
  package.json
  packages/arch/packages/alert/README.md
  packages/fields/src/types/Relationship/README.md
Labels: review me

#3423 Add filter & CRUD tests for Wysiwyg
  .changeset/lemon-bulldogs-hear.md
  packages/fields-wysiwyg-tinymce/package.json
  packages/fields-wysiwyg-tinymce/src/test-fixtures.js
Labels: review me

#3420 Add listKey argument to hooks
  .changeset/big-jeans-itch.md
  docs/api/hooks.md
  packages/keystone/lib/ListTypes/hooks.js
  packages/keystone/lib/providers/listAuth.js
Labels: review me

#3426 Default param for keystone.createContext()
  .changeset/tender-fans-smash.md
  packages/keystone/lib/Keystone/index.js
Labels: review me

#3427 Allow auth strategy plugins
  .changeset/violet-knives-travel.md
  docs/api/authentication.md
  packages/keystone/lib/Keystone/index.js
Labels: review me

#3425 Add a logging plugin
  .changeset/small-horses-push.md
  api-tests/hooks/logging-plugin.test.js
  api-tests/package.json
  packages/list-plugins/README.md
  packages/list-plugins/index.js
  packages/list-plugins/lib/logging.js
Labels: needs-clarification

#3432 Fix incorrect instructions in CHANGELOG
  packages/keystone/CHANGELOG.md
Labels: needs-clarification

#3463 Fix many-to-one-one queries
  .changeset/silver-plums-cry.md
  api-tests/relationships/many-to-one-to-one.test.js
  packages/adapter-knex/lib/adapter-knex.js
Labels: needs-clarification, review me

#3465 Remove unused dependency
  .changeset/cool-hairs-beam.md
  api-tests/package.json
  benchmarks/package.json
  demo-projects/meetup/package.json
  packages/session/package.json
  test-projects/login/package.json
Labels: needs-clarification, review me

#3487 Add CRUD tests for core field types
  .changeset/rotten-ladybugs-visit.md
  api-tests/fields.test.js
  packages/fields-cloudinary-image/src/test-fixtures.js
  packages/fields-color/src/test-fixtures.js
  packages/fields-location-google/src/test-fixtures.js
  packages/fields-markdown/src/test-fixtures.js
  packages/fields-mongoid/src/test-fixtures.js
  packages/fields-oembed/src/test-fixtures.js
  packages/fields-unsplash/src/test-fixtures.js
  packages/fields-wysiwyg-tinymce/src/test-fixtures.js
  packages/fields/src/types/CalendarDay/test-fixtures.js
  packages/fields/src/types/Checkbox/test-fixtures.js
  packages/fields/src/types/DateTime/test-fixtures.js
  packages/fields/src/types/DateTimeUtc/test-fixtures.js
  packages/fields/src/types/Decimal/test-fixtures.js
  packages/fields/src/types/File/test-fixtures.js
  packages/fields/src/types/Float/test-fixtures.js
  packages/fields/src/types/Integer/test-fixtures.js
  packages/fields/src/types/Password/test-fixtures.js
  packages/fields/src/types/Select/test-fixtures.js
  packages/fields/src/types/Text/test-fixtures.js
  packages/fields/src/types/Url/test-fixtures.js
  packages/fields/src/types/Uuid/test-fixtures.js
  packages/fields/tests/test-fixtures.js
Labels: review me

#3500 Consolidate field test scripts
  .changeset/five-jars-pretend.md
  api-tests/fields.test.js
  api-tests/fields/crud.test.js
  api-tests/fields/filter.test.js
  api-tests/fields/required.test.js
  api-tests/fields/unique.test.js
  api-tests/required.test.js
  api-tests/uniqueness/unique.test.js
  docs/tutorials/initial-data.md
  packages/fields-color/src/test-fixtures.js
  packages/fields-markdown/src/test-fixtures.js
  packages/fields-wysiwyg-tinymce/src/test-fixtures.js
  packages/fields/src/types/CalendarDay/test-fixtures.js
  packages/fields/src/types/Checkbox/test-fixtures.js
  packages/fields/src/types/DateTime/test-fixtures.js
  packages/fields/src/types/DateTimeUtc/test-fixtures.js
  packages/fields/src/types/Decimal/test-fixtures.js
  packages/fields/src/types/Float/test-fixtures.js
  packages/fields/src/types/Integer/test-fixtures.js
  packages/fields/src/types/Password/test-fixtures.js
  packages/fields/src/types/Select/test-fixtures.js
  packages/fields/src/types/Text/test-fixtures.js
  packages/fields/src/types/Url/test-fixtures.js
  packages/fields/src/types/Uuid/test-fixtures.js
  packages/fields/tests/test-fixtures.js
Labels: review me

#3501 Removed unsupported filter options for field types
  .changeset/sharp-donkeys-dance.md
  packages/fields-location-google/src/Implementation.js
  packages/fields-oembed/src/Implementation.js
  packages/fields-unsplash/src/Implementation.js
  packages/fields/src/types/File/Implementation.js
Labels: review me

#3462 Add tests for `OEmbed` field
  .changeset/tender-eyes-joke.md
  .github/workflows/tests.yml
  api-tests/fields/crud.test.js
  packages/fields-oembed/.env.example
  packages/fields-oembed/package.json
  packages/fields-oembed/src/test-fixtures.js
Labels: review me

#3473 Add filter and CRUD test for Unsplash field
  .changeset/three-melons-eat.md
  .github/workflows/tests.yml
  packages/fields-unsplash/.env.example
  packages/fields-unsplash/package.json
  packages/fields-unsplash/src/Implementation.js
  packages/fields-unsplash/src/test-fixtures.js
Labels: review me

#3476 Add filter, CRUD tests for LocationGoogle field
  .changeset/beige-eyes-flash.md
  .github/workflows/tests.yml
  packages/fields-location-google/.env.example
  packages/fields-location-google/package.json
  packages/fields-location-google/src/test-fixtures.js
Labels: needs-clarification

#3415 Add filter and CRUD tests for AutoIncrement field
  .changeset/few-icons-ring.md
  api-tests/fields/crud.test.js
  api-tests/fields/filter.test.js
  api-tests/fields/required.test.js
  api-tests/fields/unique.test.js
  packages/fields-auto-increment/package.json
  packages/fields-auto-increment/src/test-fixtures.js
  packages/fields-auto-increment/src/test-fixtures.skip.js
Labels: review me
