Repository keystonejs/keystone, pull requests merged in 2020-05, with the labels that each got.

#2889 Set the cookieSecret in tests to clear warnings
  .changeset/poor-needles-know.md
  packages/keystone/tests/Keystone.test.js
  packages/test-utils/lib/test-utils.js
Labels: needs-clarification

#2894 Remove unused prop
  .changeset/bright-papayas-agree.md
  packages/app-admin-ui/client/pages/Item/index.js
Labels: needs-clarification

#2891 Apply cosmetic changes to AppAdminUI
  .changeset/large-geese-listen.md
  packages/app-admin-ui/index.js
Labels: needs-clarification

#2892 Explicitly unpack List config items from adminMeta
  .changeset/giant-hornets-argue.md
  packages/app-admin-ui/client/providers/AdminMeta.js
Labels: needs-clarification

#2893 Add Keystone.getAdminViews()
  .changeset/curly-pumpkins-call.md
  packages/app-admin-ui/index.js
  packages/keystone/lib/Keystone/index.js
  packages/keystone/lib/List/index.js
  packages/keystone/tests/List.test.js
Labels: needs-clarification

#2908 Add List.fullPath
  .changeset/two-mice-cheat.md
  packages/app-admin-ui/client/classes/List.js
  packages/app-admin-ui/client/components/Nav/index.js
  packages/app-admin-ui/client/pages/Home/components.js
  packages/app-admin-ui/client/pages/Item/ItemTitle.js
  packages/app-admin-ui/client/pages/Item/Search.js
  packages/app-admin-ui/client/pages/Item/index.js
  packages/app-admin-ui/client/pages/List/index.js
Labels: needs-clarification

#2917 Simplify construction of adminMeta value
  .changeset/odd-cows-think.md
  packages/app-admin-ui/client/providers/AdminMeta.js
Labels: needs-clarification

#2853 Upgrade dev dependencies
  .changeset/light-masks-pay.md
  package.json
  packages/build-field-types/__fixtures__/use-babel-runtime/package.json
  packages/build-field-types/__fixtures__/uses-babel-and-throws-error/package.json
  packages/build-field-types/package.json
  packages/email/package.json
  packages/keystone/package.json
  test-projects/access-control/package.json
  test-projects/basic/package.json
  test-projects/client-validation/package.json
  test-projects/login/package.json
  test-projects/social-login/package.json
  yarn.lock
Labels: needs-clarification

#2915 Update website dependencies
  .changeset/few-mails-grab.md
  package.json
  packages/arch/packages/day-picker/package.json
  packages/fields/package.json
  website/package.json
  website/plugins/gatsby-remark-fix-links/index.js
  yarn.lock
Labels: needs-clarification

#2925 website: Apply hash link offset to H4s
  website/src/components/markdown/Heading.js
Labels: docs

#2947 Add support for arguments on Virtual fields
  .changeset/four-crabs-hug.md
  CONTRIBUTING.md
  README.md
  api-tests/Virtual.test.js
  packages/fields/src/types/Virtual/Implementation.js
  packages/fields/src/types/Virtual/README.md
Labels: needs-clarification

#2561 mention StaticServer when using LocalFileAdapter
  packages/file-adapters/README.md
Labels: merge conflict, needs-clarification

#2956 Added a password field cell view
  .changeset/dull-crabs-cheat.md
  packages/app-admin-ui/client/components/ListTable.js
  packages/fields/src/types/Password/index.js
  packages/fields/src/types/Password/views/Cell.js
Labels: admin-ui, merge conflict

#3018 Set up tests ready for iterating over multiple access configs
  .changeset/stale-crews-hear.md
  api-tests/relationships/nested-mutations/connect-singular.test.js
  api-tests/relationships/nested-mutations/create-singular.test.js
Labels: needs-clarification

#3020 Fixed typo
  docs/discussions/new-data-schema.md
Labels: needs-clarification

#2482 Enable listManageActions hook
  .changeset/chilled-eagles-compete.md
  packages/app-admin-ui/client/components/DeleteItems.js
  packages/app-admin-ui/client/components/UpdateItems.js
  packages/app-admin-ui/client/pages/List/Management.js
  packages/app-admin-ui/client/pages/List/SortSelect.js
  packages/app-admin-ui/client/pages/List/dataHooks.js
  packages/app-admin-ui/client/pages/List/index.js
  packages/app-admin-ui/client/providers/List.js
  packages/app-admin-ui/client/util.js
  packages/app-admin-ui/components/index.js
Labels: admin-ui

#3064 [Docs] Update singleton.md / Fixes typo in menu
  packages/list-plugins/singleton.md
Labels: needs-clarification

#3062 Update new-data-schema.md / Fix typo in docs text
  docs/discussions/new-data-schema.md
Labels: needs-clarification
