Repository keystonejs/keystone, pull requests merged in 2021-11, with the labels that each got.

#6836 fix documentation for itemView/listView
  packages/keystone/src/types/config/lists.ts
Labels: pr/category/website

#6846 Fix docs code size in Safari
  docs/lib/prose-lite.ts
Labels: pr/category/website

#6714 Add support for extensions with numbers (eg mp3, woff2)
  .changeset/green-bulldogs-suffer.md
  packages/keystone/src/lib/context/createFilesContext.ts
Labels: :earth_asia: pr/community

#6843 Bump dependencies
  .changeset/tall-rocks-juggle.md
  .github/workflows/tests.yml
  .nvmrc
  design-system/packages/button/package.json
  design-system/packages/core/package.json
  design-system/packages/fields/package.json
  design-system/packages/icons/package.json
  design-system/packages/loading/package.json
  design-system/packages/modals/package.json
  design-system/packages/notice/package.json
  design-system/packages/segmented-control/package.json
  design-system/packages/toast/package.json
  design-system/website/package.json
  docs/package.json
  examples-staging/auth/package.json
  examples-staging/basic/package.json
  examples-staging/ecommerce/package.json
  examples-staging/embedded-nextjs/package.json
  examples-staging/roles/package.json
  examples/custom-admin-ui-logo/package.json
  examples/document-field/package.json
  examples/testing/package.json
  package.json
  packages/cloudinary/package.json
  packages/fields-document/package.json
  packages/keystone/package.json
  packages/keystone/src/___internal-do-not-use-will-break-in-patch/admin-ui/next-config.ts
  packages/keystone/src/admin-ui/system/buildAdminUI.ts
  packages/keystone/src/admin-ui/templates/app.ts
  packages/keystone/src/scripts/build/build.ts
  packages/keystone/src/scripts/tests/build.test.ts
  packages/keystone/static/tsconfig.json
  tests/admin-ui-tests/live-reloading.test.ts
  tests/admin-ui-tests/package.json
  tests/api-tests/package.json
  tests/examples-smoke-tests/package.json
  tsconfig.json
  yarn.lock
Labels: pr/category/dependencies

#6864 add null relationship filter example
  docs/pages/docs/guides/filters.mdx
Labels: :earth_asia: issue/community

#6798 New Auth and Access Control guide
  docs/components/docs/Navigation.tsx
  docs/pages/docs/apis/auth.mdx
  docs/pages/docs/guides/access-control.mdx
  docs/pages/docs/guides/auth-and-access-control.mdx
  docs/pages/docs/guides/auth.mdx
  docs/pages/updates/index.tsx
  docs/tsconfig.json
Labels: ✏️ pr/documentation

#6904 Renovating
  .changeset/red-crabs-clean.md
  design-system/packages/core/package.json
  design-system/packages/fields/package.json
  design-system/packages/options/package.json
  docs/package.json
  examples-staging/basic/package.json
  examples-staging/ecommerce/package.json
  examples/custom-field-view/package.json
  package.json
  packages/auth/package.json
  packages/cloudinary/package.json
  packages/fields-document/package.json
  packages/keystone/package.json
  prisma-utils/package.json
  tests/admin-ui-tests/package.json
  tests/api-tests/package.json
  tests/api-tests/utils.ts
  tests/examples-smoke-tests/package.json
  yarn.lock
Labels: 🔧 pr/dependencies

#6792 Add an example using Nexus to extend the Keystone schema
  .changeset/three-beans-cross.md
  .eslintignore
  .github/workflows/tests.yml
  .prettierignore
  examples/README.md
  examples/extend-graphql-schema-nexus/.gitignore
  examples/extend-graphql-schema-nexus/CHANGELOG.md
  examples/extend-graphql-schema-nexus/README.md
  examples/extend-graphql-schema-nexus/keystone.ts
  examples/extend-graphql-schema-nexus/nexus/index.ts
  examples/extend-graphql-schema-nexus/nexus/types/Post.ts
  examples/extend-graphql-schema-nexus/nexus/types/Thing.ts
  examples/extend-graphql-schema-nexus/nexus/types/index.ts
  examples/extend-graphql-schema-nexus/package.json
  examples/extend-graphql-schema-nexus/schema.graphql
  examples/extend-graphql-schema-nexus/schema.prisma
  examples/extend-graphql-schema-nexus/schema.ts
  tests/examples-smoke-tests/extend-graphql-schema-nexus.test.ts
  yarn.lock
Labels: ✏️ pr/documentation

#6950 Update release workflow to use Node LTS
  .github/workflows/release.yml
Labels: 🔧 pr/dependencies

#6941 Text tweaks to release notes.
  docs/pages/releases/2021-11-15.mdx
  docs/pages/releases/index.mdx
Labels: 📃 pr/website

#6869 Update release notes process
  RELEASE.md
Labels: ✏️ pr/documentation

#6911 Renovating
  .changeset/happy-flies-do.md
  .changeset/tiny-impalas-call.md
  design-system/packages/button/package.json
  design-system/packages/core/package.json
  design-system/packages/core/src/utils.ts
  design-system/packages/fields/package.json
  design-system/packages/icons/package.json
  design-system/packages/loading/package.json
  design-system/packages/modals/package.json
  design-system/packages/notice/package.json
  design-system/packages/options/package.json
  design-system/packages/pill/package.json
  design-system/packages/popover/package.json
  design-system/packages/segmented-control/package.json
  design-system/packages/toast/package.json
  design-system/packages/tooltip/package.json
  design-system/website/package.json
  docs/babel.config.js
  docs/components/Header.tsx
  docs/components/Markdown.tsx
  docs/components/Page.tsx
  docs/components/docs/Sidebar.tsx
  docs/components/icons/Bulb.tsx
  docs/components/icons/Video.tsx
  docs/components/primitives/EditButton.tsx
  docs/lib/getHeadings.ts
  docs/package.json
  docs/pages/404.tsx
  docs/pages/for-content-management.tsx
  docs/pages/for-developers.tsx
  docs/pages/for-organisations.tsx
  docs/pages/index.tsx
  docs/pages/updates/index.tsx
  docs/pages/updates/roadmap.tsx
  docs/pages/why-keystone.tsx
  examples-staging/auth/package.json
  examples-staging/basic/package.json
  examples-staging/ecommerce/package.json
  examples-staging/embedded-nextjs/package.json
  examples-staging/graphql-api-endpoint/package.json
  examples-staging/roles/package.json
  examples/custom-admin-ui-logo/package.json
  examples/document-field/package.json
  examples/testing/package.json
  package.json
  packages/auth/package.json
  packages/cloudinary/package.json
  packages/fields-document/package.json
  packages/keystone/package.json
  packages/keystone/src/lib/server/createExpressServer.ts
  packages/session-store-redis/package.json
  prisma-utils/package.json
  tests/api-tests/package.json
  tests/api-tests/utils.ts
  yarn.lock
Labels: 🔧 pr/dependencies

#6961 Fix default renderer of layout block
  .changeset/shy-poets-taste.md
  packages/document-renderer/src/index.tsx
Labels: :earth_asia: issue/community

#6966 Branding page
  docs/components/icons/Download.tsx
  docs/components/icons/Nope.tsx
  docs/components/icons/index.ts
  docs/pages/branding.tsx
Labels: 📃 pr/website

#6984 Branding links
  docs/components/Footer.tsx
  docs/pages/updates/index.tsx
Labels: 📃 pr/website

#6985 Added Azure deployment example
  docs/pages/updates/index.tsx
Labels: 📃 pr/website

#6991 Added new examples to index
  docs/pages/docs/examples.tsx
Labels: 📃 pr/website
