Repository keystonejs/keystone, pull requests merged in 2021-08, with the labels that each got.

#6256 Use Next 11 in the website
  docs/babel.config.js
  docs/next-env.d.ts
  docs/next.config.js
  docs/package.json
  yarn.lock
Labels: pr/category/website

#6282 Content management update
  docs/pages/for-content-management.tsx
Labels: pr/category/website

#6283 Fixed whitespace
  docs/components/content/MWrapper.tsx
Labels: pr/category/website

#6273 Wes Bos CTA Block
  docs/components/content/AdvancedReactCta.tsx
  docs/pages/why-keystone.tsx
  docs/public/assets/wesbos-cta.jpg
Labels: pr/category/website

#6328 Fixed Hooks guide link value
  docs/pages/docs/guides/hooks.mdx
Labels: issue/category/website

#6346 Fixed markdown for bold styles
  docs/pages/releases/index.mdx
Labels: issue/category/website

#6343 Tweaking for local dev using Docker
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: pr/community

#6366 Updates nav additions
  docs/components/docs/Navigation.tsx
  docs/pages/docs/guides/index.tsx
  docs/pages/docs/index.tsx
  docs/pages/updates/index.tsx
  docs/pages/updates/keystone-5-vs-keystone-6-preview.mdx
  docs/pages/updates/roadmap.tsx
  docs/redirects.js
Labels: pr/category/website

#6374 Updated URLs
  docs/pages/docs/guides/custom-fields.mdx
Labels: issue/category/website

#6387 Added upgrade notices to GraphQL API related pages
  docs/pages/docs/apis/filters.mdx
  docs/pages/docs/apis/graphql.mdx
  docs/pages/docs/guides/filters.mdx
Labels: issue/category/website

#6360 [WIP] Related content links
  docs/components/RelatedContent.tsx
  docs/components/primitives/Well.tsx
  docs/pages/docs/apis/auth.mdx
  docs/pages/docs/apis/config.mdx
  docs/pages/docs/apis/context.mdx
  docs/pages/docs/apis/db-items.mdx
  docs/pages/docs/apis/fields.mdx
  docs/pages/docs/apis/filters.mdx
  docs/pages/docs/apis/graphql.mdx
  docs/pages/docs/apis/hooks.mdx
  docs/pages/docs/apis/list-items.mdx
  docs/pages/docs/apis/schema.mdx
  docs/pages/docs/apis/session.mdx
  docs/pages/docs/guides/cli.mdx
  docs/pages/docs/guides/custom-admin-ui-logo.mdx
  docs/pages/docs/guides/custom-admin-ui-navigation.mdx
  docs/pages/docs/guides/custom-admin-ui-pages.mdx
  docs/pages/docs/guides/custom-fields.mdx
  docs/pages/docs/guides/document-field-demo.mdx
  docs/pages/docs/guides/document-fields.mdx
  docs/pages/docs/guides/filters.mdx
  docs/pages/docs/guides/hooks.mdx
  docs/pages/docs/guides/index.tsx
  docs/pages/docs/guides/relationships.mdx
  docs/pages/docs/guides/testing.mdx
  docs/pages/docs/guides/virtual-fields.mdx
  docs/pages/docs/walkthroughs/embedded-mode-with-sqlite-nextjs.mdx
  docs/pages/docs/walkthroughs/getting-started-with-create-keystone-app.mdx
Labels: issue/category/website

#6400 Added 2x testimonials
  docs/pages/for-developers.tsx
  docs/public/assets/benoit-richert.jpg
  docs/public/assets/divslingerx.jpg
Labels: pr/category/website

#6385 fixed count in relationship field count mode
  .changeset/cool-rings-obey.md
  packages/keystone/src/fields/types/relationship/views/index.tsx
Labels: pr/community
