Repository keystonejs/keystone, pull requests merged in 2023-08, with the labels that each got.

#8726 Adds new `random` identifier type
  .changeset/add-cuid2.md
  .changeset/add-random-id.md
  .changeset/fix-field-widths.md
  .changeset/fix-responsive-ui.md
  examples/custom-id/keystone.ts
  examples/custom-id/schema.ts
  examples/default-values/schema.ts
  packages/core/package.json
  packages/core/src/lib/config.ts
  packages/core/src/lib/createSystem.ts
  packages/core/src/lib/id-field.ts
  packages/core/src/types/config/lists.ts
  packages/core/src/types/next-fields.ts
  pnpm-lock.yaml
  tests/api-tests/id-field.test.ts
  tests/api-tests/package.json
Labels: upcoming

#8743 Fixes `session` type as `any` when using `.keystone/types` `Lists` as your root type
  .changeset/enable-sourcemap-esbuild.md
  .changeset/fix-session-types.md
  examples/custom-output-paths/my-types.ts
  examples/custom-session/schema.ts
  examples/extend-graphql-schema-nexus/keystone-types.ts
  examples/usecase-roles/schema.ts
  packages/core/src/lib/schema-type-printer.tsx
  packages/core/src/schema.ts
  packages/core/src/types/config/lists.ts
  packages/core/src/types/type-info.ts
  tests/cli-tests/__snapshots__/artifacts.test.ts.snap
Labels: 🐛 bug

#8397 Remove `ExtendGraphqlSchema` type alias
  .changeset/no-extend-type.md
  docs/pages/docs/config/config.md
  packages/core/src/index.ts
  packages/core/src/types/config/index.ts
Labels: upcoming, breaking

#8722 Use console.error for Prisma errors
  .changeset/more-errors-please.md
  packages/core/src/lib/core/graphql-errors.ts
Labels: blocked, upcoming, breaking

#8698 fix(cli): regenerate prisma schema during `keystone prisma ..` commands
  .changeset/fix-frozen-prisma.md
  packages/core/src/scripts/prisma.ts
Labels: breaking

#8764 Remove `context.exitSudo()`
  .changeset/no-exit-sudo.md
  docs/pages/docs/context/overview.md
  packages/core/src/lib/context/createContext.ts
  packages/core/src/scripts/prisma.ts
  packages/core/src/types/context.ts
  tests/api-tests/admin-meta.test.ts
Labels: breaking
