Repository keystonejs/keystone, pull requests merged in 2024-08, with the labels that each got.

#9235 Add support for developers to replace the default esbuild configuration
  .changeset/add-custom-esbuild.md
  examples/custom-esbuild/README.md
  examples/custom-esbuild/esbuild.keystone.ts
  examples/custom-esbuild/keystone.ts
  examples/custom-esbuild/package.json
  examples/custom-esbuild/sandbox.config.json
  examples/custom-esbuild/schema.graphql
  examples/custom-esbuild/schema.prisma
  examples/custom-esbuild/schema.ts
  packages/core/src/lib/esbuild.ts
  packages/core/src/scripts/build.ts
  packages/core/src/scripts/dev.ts
  packages/core/src/scripts/esbuild.ts
  packages/core/src/scripts/migrate.ts
  pnpm-lock.yaml
Labels: help wanted

#9272 Docs: example links fixing + table of contents fixes
  docs/app/(site)/blog/[post]/page-client.tsx
  docs/app/(site)/docs/[...rest]/page-client.tsx
  docs/app/(site)/docs/[...rest]/page.tsx
  docs/components/Markdoc.tsx
  docs/components/docs/DocsLayoutClient.tsx
  docs/content/examples/auth.yaml
  docs/content/examples/azure.yaml
  docs/content/examples/blog.yaml
  docs/content/examples/custom-admin-ui-navigation.yaml
  docs/content/examples/custom-admin-ui-pages.yaml
  docs/content/examples/custom-admin-ui.yaml
  docs/content/examples/custom-field-type.yaml
  docs/content/examples/custom-field-view.yaml
  docs/content/examples/default-values.yaml
  docs/content/examples/document-field-customisation.yaml
  docs/content/examples/document-field.yaml
  docs/content/examples/extend-express-app.yaml
  docs/content/examples/extend-graphql-schema-nexus.yaml
  docs/content/examples/extend-graphql-schema-ts.yaml
  docs/content/examples/extend-graphql-schema.yaml
  docs/content/examples/heroku.yaml
  docs/content/examples/json-field.yaml
  docs/content/examples/next-js.yaml
  docs/content/examples/railway.yaml
  docs/content/examples/singleton.yaml
  docs/content/examples/task-manager.yaml
  docs/content/examples/testing.yaml
  docs/content/examples/virtual-field.yaml
  docs/markdoc/headings.ts
  docs/public/sitemap-0.xml
Labels: documentation

#9273 Fix Prisma errors not showing when a Prisma migration errors internally
  .changeset/fix-prisma-migrate.md
  packages/core/src/lib/migrations.ts
  packages/core/src/scripts/dev.ts
  tests/cli-tests/migrations.test.ts
Labels: 🐛 bug

#9275 Fix schemas for `create-keystone-app`
  .changeset/moved-create-app.md
  packages/create/starter/auth.ts
  packages/create/starter/package.json
  packages/create/starter/schema.graphql
  packages/create/starter/schema.prisma
Labels: 🐛 bug, help wanted

#9301 Fix transaction passthrough types, and add linting for examples
  .github/workflows/tests_ci.yml
  examples/custom-output-paths/my-types.ts
  examples/extend-graphql-schema-nexus/keystone-types.ts
  packages/core/src/lib/typescript-schema-printer.ts
  packages/core/src/types/context.ts
  packages/core/src/types/type-info.ts
  packages/core/src/types/type-tests.ts
  tests/cli-tests/__snapshots__/artifacts.test.ts.snap
Labels: 🐛 bug

#9278 Fix validation hook merge function passthrough
  .changeset/fix-hooks-errors.md
  packages/core/src/fields/resolve-hooks.ts
Labels: 🐛 bug

#9293 Add buttondown for the `/docs` newsletter subscription using server actions 😎
  .gitignore
  docs/.env.example
  docs/app/actions.ts
  docs/components/SubscribeForm.tsx
Labels: documentation

#9314 Remove pre-built schemas from `create-keystone-app`
  .changeset/cka-fix.md
  packages/create/src/index.ts
Labels: 🐛 bug, help wanted
