Repository keystonejs/keystone, pull requests merged in 2025-02, with the labels that each got.

#9234 Add support for [field].graphql.isNonNull: true
  .changeset/add-isnonnull-true.md
  packages/core/src/fields/non-null-graphql.ts
  packages/core/src/lib/core/initialise-lists.ts
  packages/core/src/lib/typescript-schema-printer.ts
  packages/core/src/types/config/fields.ts
Labels: breaking

#9421 Next 15 and react 19 🚀
  .changeset/bump-next.md
  .changeset/bump-react.md
  docs/app/(site)/blog/[post]/page.tsx
  docs/app/(site)/docs/[...rest]/page.tsx
  docs/components/Header.tsx
  docs/components/Markdoc.tsx
  docs/components/content/CustomerCard.tsx
  docs/package.json
  docs/tsconfig.json
  examples/auth-magic-link/package.json
  examples/cloudinary/package.json
  examples/custom-admin-ui-logo/package.json
  examples/custom-admin-ui-navigation/package.json
  examples/custom-admin-ui-pages/package.json
  examples/custom-field/package.json
  examples/custom-output-paths/package.json
  examples/custom-session-next-auth/package.json
  examples/document-field-customisation/keystone-server/package.json
  examples/document-field-customisation/nextjs-frontend/package.json
  examples/document-field/package.json
  examples/extend-graphql-subscriptions/package.json
  examples/framework-astro/package.json
  examples/framework-nextjs-app-directory/next.config.mjs
  examples/framework-nextjs-app-directory/package.json
  examples/framework-nextjs-pages-directory/package.json
  examples/framework-nextjs-two-servers/nextjs-frontend/package.json
  examples/framework-remix/package.json
  examples/graphql-ts-gql/package.json
  package.json
  packages/auth/package.json
  packages/cloudinary/package.json
  packages/core/package.json
  packages/core/src/___internal-do-not-use-will-break-in-patch/admin-ui/pages/ListPage/FilterList.tsx
  packages/core/src/scripts/build.ts
  packages/document-renderer/package.json
  packages/document-renderer/src/index.tsx
  packages/fields-document/package.json
  packages/fields-document/src/DocumentEditor/component-blocks/component-block-render.tsx
  packages/fields-document/src/DocumentEditor/lists.test.tsx
  packages/fields-document/src/DocumentEditor/primitives/BlockPopover.tsx
  packages/fields-document/src/DocumentEditor/tests/utils.tsx
  pnpm-lock.yaml
  tests/sandbox/package.json
Labels: dependencies, breaking

#9204 Remove deprecated hooks
  .changeset/chilled-moons-walk.md
  examples/custom-field/2-stars-field/index.ts
  examples/custom-field/schema.ts
  examples/field-groups/schema.ts
  examples/hooks/schema.ts
  examples/reuse/schema.ts
  examples/usecase-roles/schema.ts
  examples/usecase-versioning/schema.ts
  packages/core/src/fields/non-null-graphql.ts
  packages/core/src/fields/resolve-hooks.ts
  packages/core/src/fields/types/bigInt/index.ts
  packages/core/src/fields/types/calendarDay/index.ts
  packages/core/src/fields/types/decimal/index.ts
  packages/core/src/fields/types/file/index.ts
  packages/core/src/fields/types/float/index.ts
  packages/core/src/fields/types/image/index.ts
  packages/core/src/fields/types/integer/index.ts
  packages/core/src/fields/types/multiselect/index.ts
  packages/core/src/fields/types/password/index.ts
  packages/core/src/fields/types/select/index.ts
  packages/core/src/fields/types/text/index.ts
  packages/core/src/fields/types/timestamp/index.ts
  packages/core/src/lib/core/initialise-lists.ts
  packages/core/src/schema.ts
  packages/core/src/types/config/hooks.ts
  packages/fields-document/src/structure.ts
Labels: breaking

#9499 Fix relationship fields incorrectly being included in default search fields
  packages/core/src/lib/core/initialise-lists.ts
  packages/core/src/lib/create-admin-meta.ts
Labels: 🐛 bug

#9507 Fix relationship field UI removing selected item after focus and blur in some cases
  packages/core/src/fields/types/relationship/views/ComboboxSingle.tsx
  packages/core/src/fields/types/relationship/views/index.tsx
  tests/admin-ui-tests/relations.test.ts
Labels: 🐛 bug

#9508 Fix item form being shown when item is not found
  packages/core/src/___internal-do-not-use-will-break-in-patch/admin-ui/pages/ItemPage/index.tsx
Labels: 🐛 bug
